apiVersion: v1
kind: Service
metadata:
  labels:
    app: diarkis
    component: bot
  name: bot
  namespace: bot
spec:
  ports:
    - name: bot
      port: 80
      protocol: TCP
      targetPort: 9500
  selector:
    app: diarkis
    component: bot
  type: LoadBalancer
