// © 2019-2024 Diarkis Inc. All rights reserved.

// Code generated by "./generator ./config"; DO NOT EDIT.
package packets

// Packet Format
//
//	 No.    | Name             | Type      | Size    |
//	--------|------------------|-----------|---------|
//	 0.     | ticketType       | int       | 1 byte  |
//	--------|------------------|-----------|---------|
type IssueTicketReq struct {
	TicketType uint8 `json:"ticketType"`
}

func CreateIssueTicketReq(values *IssueTicketReq) []byte {
	var bytes []byte

	// Append ticketType
	bytes = append(bytes, values.TicketType)

	return bytes
}
func ParseIssueTicketReq(payload []byte) *IssueTicketReq {
	var parsed IssueTicketReq

	// Parse ticketType
	parsed.TicketType = payload[0]

	return &parsed
}
