buildSettings:
  root: .
  goVersion: 1.16.5
  env:
    GOOS:
    GOARCH:
    CGO_CFLAGS: -I${PROJECT_DIR}
    CGO_LDFLAGS: -L${PROJECT_DIR} -Wl,-rpath,${PROJECT_DIR}
  projects:
    http:
      target: cmd/http/main.go
      output: remote_bin/http
    udp:
      target: cmd/udp/main.go
      output: remote_bin/udp
    tcp:
      target: cmd/tcp/main.go
      output: remote_bin/tcp
    ws:
      target: cmd/ws/main.go
      output: remote_bin/ws
diarkis:
  project_id: 4934392951
  builder_token: b3bf074e-1d32-40cc-bcfc-cd610e271e3f
