// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package onlinestatus

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// OnlineStatusResponseVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const OnlineStatusResponseVer uint8 = 2

// OnlineStatusResponseCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const OnlineStatusResponseCmd uint16 = 500

// OnlineStatusResponse represents the command protocol data structure.
type OnlineStatusResponse struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd            uint16
	Status         uint16
	UserStatusList []*UserStatus
}

// NewOnlineStatusResponse creates a new instance of OnlineStatusResponse struct.
func NewOnlineStatusResponse() *OnlineStatusResponse {
	return &OnlineStatusResponse{Ver: 2, Cmd: 500, Status: 0, UserStatusList: make([]*UserStatus, 0)}
}

// Pack encodes OnlineStatusResponse struct to a byte array to be delivered over the command.
func (proto *OnlineStatusResponse) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	/* uint16 */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(proto.Status))

	/* []UserStatus */
	userStatusListLengthBytes := make([]byte, 2)
	userStatusListLength := len(proto.UserStatusList)
	binary.BigEndian.PutUint16(userStatusListLengthBytes, uint16(userStatusListLength))
	bytes = append(bytes, userStatusListLengthBytes...)
	for i := 0; i < userStatusListLength; i++ {
		userStatusListSizeBytes := make([]byte, 2)
		userStatusListPacked := proto.UserStatusList[i].Pack()
		binary.BigEndian.PutUint16(userStatusListSizeBytes, uint16(len(userStatusListPacked)))
		bytes = append(bytes, userStatusListSizeBytes...)
		bytes = append(bytes, userStatusListPacked...)
	}

	// done
	return bytes
}

// Unpack decodes the command payload byte array to OnlineStatusResponse struct.
func (proto *OnlineStatusResponse) Unpack(bytes []byte) error {
	unpackErr := errors.New("OnlineStatusResponseUnpackError")
	if len(bytes) < 4 {
		return unpackErr
	}

	offset := 0

	/* uint16 */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Status: %w", unpackErr)
	}
	proto.Status = binary.BigEndian.Uint16(bytes[offset : offset+2])
	offset += 2

	/* []UserStatus */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack UserStatusList: %w", unpackErr)
	}
	userStatusListLength := int(binary.BigEndian.Uint16((bytes[offset : offset+2])))
	offset += 2
	proto.UserStatusList = make([]*UserStatus, userStatusListLength)
	for i := 0; i < userStatusListLength; i++ {
		if offset+2 > len(bytes) {
			return fmt.Errorf("payload too short to unpack UserStatusList at index %d: %w", i, unpackErr)
		}
		userStatusListSize := int(binary.BigEndian.Uint16((bytes[offset : offset+2])))
		offset += 2
		if userStatusListSize+offset > len(bytes) {
			return fmt.Errorf("payload too short to unpack UserStatusList at index %d: %w", i, unpackErr)
		}
		userStatusListBytes := bytes[offset : offset+userStatusListSize : offset+userStatusListSize]
		item := &UserStatus{Ver: 2, Cmd: 500}
		if err := item.Unpack(userStatusListBytes); err != nil {
			return fmt.Errorf("payload too short to unpack UserStatusList at index %d: %w", i, err)
		}
		proto.UserStatusList[i] = item
		offset += userStatusListSize
	}

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *OnlineStatusResponse) PackedSize() int {
	var packedSize = 0
	packedSize += 2 // Status
	// UserStatusList
	packedSize += 2
	for i := range proto.UserStatusList {
		packedSize += proto.UserStatusList[i].PackedSize()
	}
	return packedSize
}

func (proto *OnlineStatusResponse) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("Status = ", proto.Status))
	for i, item := range proto.UserStatusList {
		list = append(list, fmt.Sprint("UserStatusList[", i, "] = ", "[", item.String(), "]"))
	}
	return strings.Join(list, " | ")
}

func (proto *OnlineStatusResponse) GetVer() uint8 {
	return proto.Ver
}
func (proto *OnlineStatusResponse) GetCmd() uint16 {
	return proto.Cmd
}
