// © 2019-2025 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package onlinestatus

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// UserStatusVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const UserStatusVer uint8 = 0

// UserStatusCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const UserStatusCmd uint16 = 0

// UserStatus represents the command protocol data structure.
type UserStatus struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd         uint16
	InRoom      bool
	SessionData []*UserSessionData
	UID         string
}

// NewUserStatus creates a new instance of UserStatus struct.
func NewUserStatus() *UserStatus {
	return &UserStatus{Ver: 0, Cmd: 0, InRoom: false, SessionData: make([]*UserSessionData, 0), UID: ""}
}

// Pack encodes UserStatus struct to a byte array to be delivered over the command.
func (proto *UserStatus) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	var _packedBooleanBytes [1]byte
	_ = _packedBooleanBytes
	if proto.InRoom {
		_packedBooleanBytes[0] |= (1 << 0)
	}
	/* uint8 */
	bytes = append(bytes, _packedBooleanBytes[0])
	/* []UserSessionData */
	sessionDataLengthBytes := make([]byte, 2)
	sessionDataLength := len(proto.SessionData)
	binary.BigEndian.PutUint16(sessionDataLengthBytes, uint16(sessionDataLength))
	bytes = append(bytes, sessionDataLengthBytes...)
	for i := 0; i < sessionDataLength; i++ {
		sessionDataSizeBytes := make([]byte, 2)
		sessionDataPacked := proto.SessionData[i].Pack()
		binary.BigEndian.PutUint16(sessionDataSizeBytes, uint16(len(sessionDataPacked)))
		bytes = append(bytes, sessionDataSizeBytes...)
		bytes = append(bytes, sessionDataPacked...)
	}

	/* string */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.UID)))
	bytes = append(bytes, []byte(proto.UID)...)

	// done
	return bytes
}

// Unpack decodes the command payload byte array to UserStatus struct.
func (proto *UserStatus) Unpack(bytes []byte) error {
	unpackErr := errors.New("UserStatusUnpackError")
	if len(bytes) < 5 {
		return unpackErr
	}

	offset := 0

	proto.InRoom = (uint8(bytes[offset+0]) & (1 << 0)) != 0
	offset += 1

	/* []UserSessionData */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack SessionData: %w", unpackErr)
	}
	sessionDataLength := int(binary.BigEndian.Uint16((bytes[offset : offset+2])))
	offset += 2
	proto.SessionData = make([]*UserSessionData, sessionDataLength)
	for i := 0; i < sessionDataLength; i++ {
		if offset+2 > len(bytes) {
			return fmt.Errorf("payload too short to unpack SessionData at index %d: %w", i, unpackErr)
		}
		sessionDataSize := int(binary.BigEndian.Uint16((bytes[offset : offset+2])))
		offset += 2
		if sessionDataSize+offset > len(bytes) {
			return fmt.Errorf("payload too short to unpack SessionData at index %d: %w", i, unpackErr)
		}
		sessionDataBytes := bytes[offset : offset+sessionDataSize : offset+sessionDataSize]
		item := &UserSessionData{Ver: 0, Cmd: 0}
		if err := item.Unpack(sessionDataBytes); err != nil {
			return fmt.Errorf("payload too short to unpack SessionData at index %d: %w", i, err)
		}
		proto.SessionData[i] = item
		offset += sessionDataSize
	}

	/* string */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack UID: %w", unpackErr)
	}
	uIDSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if uIDSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack UID: %w", unpackErr)
	}
	offset += 2
	proto.UID = string(bytes[offset : offset+uIDSize : offset+uIDSize])
	offset += uIDSize

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *UserStatus) PackedSize() int {
	var packedSize = 0
	// SessionData
	packedSize += 2
	for i := range proto.SessionData {
		packedSize += proto.SessionData[i].PackedSize()
	}
	packedSize += 2 + len(proto.UID) // UID
	packedSize += 1                  // packed booleans length
	return packedSize
}

func (proto *UserStatus) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("InRoom = ", proto.InRoom))
	for i, item := range proto.SessionData {
		list = append(list, fmt.Sprint("SessionData[", i, "] = ", "[", item.String(), "]"))
	}
	list = append(list, fmt.Sprint("UID = ", proto.UID))
	return strings.Join(list, " | ")
}

func (proto *UserStatus) GetVer() uint8 {
	return proto.Ver
}
func (proto *UserStatus) GetCmd() uint16 {
	return proto.Cmd
}
