// © 2019-2025 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package onlinestatus

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// UserSessionDataVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const UserSessionDataVer uint8 = 0

// UserSessionDataCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const UserSessionDataCmd uint16 = 0

// UserSessionData represents the command protocol data structure.
type UserSessionData struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd  uint16
	ID   string
	Type uint8
}

// NewUserSessionData creates a new instance of UserSessionData struct.
func NewUserSessionData() *UserSessionData {
	return &UserSessionData{Ver: 0, Cmd: 0, ID: "", Type: 0}
}

// Pack encodes UserSessionData struct to a byte array to be delivered over the command.
func (proto *UserSessionData) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	/* string */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.ID)))
	bytes = append(bytes, []byte(proto.ID)...)

	/* uint8 */
	bytes = append(bytes, proto.Type)

	// done
	return bytes
}

// Unpack decodes the command payload byte array to UserSessionData struct.
func (proto *UserSessionData) Unpack(bytes []byte) error {
	unpackErr := errors.New("UserSessionDataUnpackError")
	if len(bytes) < 3 {
		return unpackErr
	}

	offset := 0

	/* string */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack ID: %w", unpackErr)
	}
	iDSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if iDSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack ID: %w", unpackErr)
	}
	offset += 2
	proto.ID = string(bytes[offset : offset+iDSize : offset+iDSize])
	offset += iDSize

	/* uint8 */
	if offset+1 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Type: %w", unpackErr)
	}
	proto.Type = uint8(bytes[offset])
	offset++

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *UserSessionData) PackedSize() int {
	var packedSize = 0
	packedSize += 2 + len(proto.ID) // ID
	packedSize += 1                 // Type
	return packedSize
}

func (proto *UserSessionData) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("ID = ", proto.ID))
	list = append(list, fmt.Sprint("Type = ", proto.Type))
	return strings.Join(list, " | ")
}

func (proto *UserSessionData) GetVer() uint8 {
	return proto.Ver
}
func (proto *UserSessionData) GetCmd() uint16 {
	return proto.Cmd
}
