namespace: dev0
bases:
  - ../../base

# build target
patches:
  - http/deploy.yaml
  - udp/deploy.yaml
  - tcp/deploy.yaml
  
configMapGenerator:
- name: shared-conf
  behavior: replace
  files:
    - shared/conf/field.json
    - shared/conf/group.json
    - shared/conf/log.json
    - shared/conf/matching.json
    - shared/conf/mesh.json
    
- name: http-conf
  behavior: replace
  files:
    - http/conf/main.json
    
- name: udp-conf
  behavior: replace  
  files:
    - udp/conf/main.json

- name: tcp-conf
  behavior: replace  
  files:
    - tcp/conf/main.json
