## The following is a set of default values for prometheus server helm chart which enable remoteWrite to AMP
## For the rest of prometheus helm chart values see: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
##
serviceAccounts:
  server:
    name: amp-iamproxy-ingest-service-account
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::026090531721:role/amp-iamproxy-ingest-role
server:
  persistentVolume:
    enabled: false
  remoteWrite:
    - url: https://aps-workspaces.ap-northeast-1.amazonaws.com/workspaces/ws-7f6d1bda-ad9a-494e-8177-43364f222190/api/v1/remote_write
      sigv4:
        region: ap-northeast-1
      queue_config:
        max_samples_per_send: 1000
        max_shards: 200
        capacity: 2500

alertmanager:
  persistence:
    enabled: false

extraScrapeConfigs: |
  - job_name: diarkis
    metrics_path: /metrics/prometheus/v/3
    static_configs:
      - targets:
          - http.dev-v0.svc.cluster.local
          - http.dev-v1.svc.cluster.local
