// Code generated by Diarkis Puffer module: DO NOT EDIT
//
// Generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

#pragma once

#define MAX_ELEMENTS 65535

#include <stdint.h>
#include <sstream>
#include <algorithm>
#include <diarkis/common.h>
#include <diarkis/packet/BigEndian.h>

using namespace Diarkis::Packet::Utils::BigEndian;




// Push the LoD data to the client.
class BroadcastLoDPush
{
	public:
		const uint8_t ver = 2;
		const uint16_t cmd = 1001;

		// Data for synchronization
		Diarkis::StdVector<uint8_t> payload;

	bool Pack(uint8_t* _data, size_t _size, size_t& _packedBytes) const
	{
		size_t _requiredLen = Length();
		if (_requiredLen > _size || _requiredLen > MAX_ELEMENTS)
		{
			return false;
		}

		size_t _offset = 0;

		/* Diarkis::StdVector<uint8_t> */
		size_t _payloadSize = payload.size();
		PutUint16(_data + _offset, (uint16_t)_payloadSize);
		_offset += sizeof(uint16_t);
		std::copy(payload.data(), payload.data() + _payloadSize, _data + _offset);
		_offset += _payloadSize;


		_packedBytes = _offset;
		return true;
	}

	bool Unpack(const uint8_t* _data, size_t _size, size_t& _unpackedBytes)
	{
		if (_size < 2)
		{
			return false;
		}

		size_t _offset = 0;
		_unpackedBytes = 0;

		/* Diarkis::StdVector<uint8_t> */
		if (_offset + sizeof(uint16_t) > _size) // array size header
		{
			return false; // payload too short
		}
		uint16_t _payloadSize = GetUint16(_data + _offset);
		_offset += sizeof(uint16_t);
		if (_offset + _payloadSize * sizeof(uint8_t) > _size)
		{
			return false; // payload too short
		}
		payload.resize(_payloadSize);
		std::copy(_data + _offset, _data + _offset + _payloadSize, payload.data());
		_offset += _payloadSize;


		_unpackedBytes = _offset;
		return true;
	}

	size_t Length() const
	{
		size_t len = 0;
		len += sizeof(uint16_t) + (payload.size() * sizeof(uint8_t)); // payload
		return len;
	}

	size_t AlignedLength(size_t _align) const
	{
		size_t _original = Length();
	
		// Align must be non-zero
		if (_align == 0)
		{
			return _original;
		}
	
		if (_original % _align)
		{
			_original += _align - (_original % _align);
		}
		return _original;
	}

	Diarkis::StdString ToString(int _indent = 0)
	{
		Diarkis::StdStringStream ss;
		Diarkis::StdString spaces = "";
		if (_indent)
		{
			spaces = Diarkis::StdString(_indent, ' ');
		}

		ss << spaces << "payload=";
		for (const auto& e : payload)
		{
			ss << std::to_string(e) << " ";
		}
		ss << "\n";

		return ss.str();
	}

};


