// Code generated by Diarkis Puffer module: DO NOT EDIT
//
// Generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

#pragma once

#define MAX_ELEMENTS 65535

#include <stdint.h>
#include <sstream>
#include <algorithm>
#include <diarkis/common.h>
#include <diarkis/packet/BigEndian.h>

using namespace Diarkis::Packet::Utils::BigEndian;




// Response the LoD information of the room.
class GetLoDInfoResponse
{
	public:
		const uint8_t ver = 2;
		const uint16_t cmd = 1002;

		// The maximum distance for far characters (centimeters)
		int32_t maxDistanceForFar = 0;
		// The maximum distance for nearby characters (centimeters)
		int32_t maxDistanceForNearby = 0;
		// Synchronization interval for far characters (milliseconds)
		int32_t syncIntervalForFar = 0;
		// Synchronization interval for nearby characters (milliseconds)
		int32_t syncIntervalForNearby = 0;

	bool Pack(uint8_t* _data, size_t _size, size_t& _packedBytes) const
	{
		size_t _requiredLen = Length();
		if (_requiredLen > _size || _requiredLen > MAX_ELEMENTS)
		{
			return false;
		}

		size_t _offset = 0;

		/* int32_t */
		PutUint32(_data + _offset, (uint32_t)maxDistanceForFar);
		_offset += sizeof(int32_t);

		/* int32_t */
		PutUint32(_data + _offset, (uint32_t)maxDistanceForNearby);
		_offset += sizeof(int32_t);

		/* int32_t */
		PutUint32(_data + _offset, (uint32_t)syncIntervalForFar);
		_offset += sizeof(int32_t);

		/* int32_t */
		PutUint32(_data + _offset, (uint32_t)syncIntervalForNearby);
		_offset += sizeof(int32_t);


		_packedBytes = _offset;
		return true;
	}

	bool Unpack(const uint8_t* _data, size_t _size, size_t& _unpackedBytes)
	{
		if (_size < 16)
		{
			return false;
		}

		size_t _offset = 0;
		_unpackedBytes = 0;

		/* int32_t */
		if (_offset + sizeof(int32_t) > _size)
		{
			return false; // payload too short
		}
		maxDistanceForFar = (int32_t)GetUint32(_data + _offset);
		_offset += sizeof(int32_t);

		/* int32_t */
		if (_offset + sizeof(int32_t) > _size)
		{
			return false; // payload too short
		}
		maxDistanceForNearby = (int32_t)GetUint32(_data + _offset);
		_offset += sizeof(int32_t);

		/* int32_t */
		if (_offset + sizeof(int32_t) > _size)
		{
			return false; // payload too short
		}
		syncIntervalForFar = (int32_t)GetUint32(_data + _offset);
		_offset += sizeof(int32_t);

		/* int32_t */
		if (_offset + sizeof(int32_t) > _size)
		{
			return false; // payload too short
		}
		syncIntervalForNearby = (int32_t)GetUint32(_data + _offset);
		_offset += sizeof(int32_t);


		_unpackedBytes = _offset;
		return true;
	}

	size_t Length() const
	{
		size_t len = 0;
		len += sizeof(int32_t); // maxDistanceForFar
		len += sizeof(int32_t); // maxDistanceForNearby
		len += sizeof(int32_t); // syncIntervalForFar
		len += sizeof(int32_t); // syncIntervalForNearby
		return len;
	}

	size_t AlignedLength(size_t _align) const
	{
		size_t _original = Length();
	
		// Align must be non-zero
		if (_align == 0)
		{
			return _original;
		}
	
		if (_original % _align)
		{
			_original += _align - (_original % _align);
		}
		return _original;
	}

	Diarkis::StdString ToString(int _indent = 0)
	{
		Diarkis::StdStringStream ss;
		Diarkis::StdString spaces = "";
		if (_indent)
		{
			spaces = Diarkis::StdString(_indent, ' ');
		}

		ss << spaces << "maxDistanceForFar=" << std::to_string(maxDistanceForFar) << "\n";

		ss << spaces << "maxDistanceForNearby=" << std::to_string(maxDistanceForNearby) << "\n";

		ss << spaces << "syncIntervalForFar=" << std::to_string(syncIntervalForFar) << "\n";

		ss << spaces << "syncIntervalForNearby=" << std::to_string(syncIntervalForNearby) << "\n";

		return ss.str();
	}

};


