// Code generated by Diarkis Puffer module: DO NOT EDIT
//
// Generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

#pragma once

#define MAX_ELEMENTS 65535

#include <stdint.h>
#include <sstream>
#include <algorithm>
#include <diarkis/common.h>
#include <diarkis/packet/BigEndian.h>

using namespace Diarkis::Packet::Utils::BigEndian;




// Get the LoD information of the room.
class GetLoDInfo
{
	public:
		const uint8_t ver = 2;
		const uint16_t cmd = 1002;



	bool Pack(uint8_t* _data, size_t _size, size_t& _packedBytes) const
	{
		size_t _requiredLen = Length();
		if (_requiredLen > _size || _requiredLen > MAX_ELEMENTS)
		{
			return false;
		}

		size_t _offset = 0;



		_packedBytes = _offset;
		return true;
	}

	bool Unpack(const uint8_t* _data, size_t _size, size_t& _unpackedBytes)
	{
		if (_size < 0)
		{
			return false;
		}

		size_t _offset = 0;
		_unpackedBytes = 0;



		_unpackedBytes = _offset;
		return true;
	}

	size_t Length() const
	{
		size_t len = 0;
		return len;
	}

	size_t AlignedLength(size_t _align) const
	{
		size_t _original = Length();
	
		// Align must be non-zero
		if (_align == 0)
		{
			return _original;
		}
	
		if (_original % _align)
		{
			_original += _align - (_original % _align);
		}
		return _original;
	}

	Diarkis::StdString ToString(int _indent = 0)
	{
		Diarkis::StdStringStream ss;
		Diarkis::StdString spaces = "";
		if (_indent)
		{
			spaces = Diarkis::StdString(_indent, ' ');
		}


		return ss.str();
	}

};


