apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mars
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: component
                    operator: In
                    values:
                      - http
              topologyKey: kubernetes.io/hostname