apiVersion: v1
kind: Service
metadata:
  name: http
  labels:
    component: http
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    component: http
  ports:
    - port: 80
      targetPort: 7000
      name: http
      protocol: TCP
