apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp
  labels:
    component: tcp
spec:
  template:
    spec:
      containers:
      - name: tcp
        image: tcp
        resources:
          limits:
            cpu: "200m"
          requests:
            cpu: "200m"
        securityContext:
          runAsUser: 1000
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
        env:
          - name: DIARKIS_CLOUD_ENV
            value: AWS
