// Code generated by Diarkis Puffer module: DO NOT EDIT
//
// Generated by Diarkis Version $(DIARKIS_VER)
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements
using System;
using System.Text;
using System.Collections.Generic;

namespace Diarkis { 
public class $(PROTOCOL_NAME)
{

  public static byte ver {
    get => $(VER);
  }
  public static ushort cmd {
    get => $(CMD);
  }

$(PROPERTIES)

  public byte[] Pack()
  {
    byte[] bytes = new byte[0];

$(PACK_LOGIC)
    // done
    return bytes;
  }

  public bool Unpack(byte[] bytes)
  {
    if (bytes.Length < $(MIN_BYTES_SIZE))
    {
      return false;
    }
$(OFFSET_INIT)$(UNPACK_LOGIC)

    return true;
  }

  public override string ToString()
  {
    List<string> list = new List<string>();
$(DEBUG_LOGIC)
    return string.Join(" | ", list);
  }

}
}