// © 2019-2024 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// # Auto-generated by Diarkis Version 1.0.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements
package custom

import "errors"
import "fmt"
import "strings"

// AttackVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const AttackVer uint8 = 2

// AttackCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const AttackCmd uint16 = 300

// Attack represents the command protocol data structure.
type Attack struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd  uint16
	Type uint8
}

// NewAttack creates a new instance of Attack struct.
func NewAttack() *Attack {
	return &Attack{Ver: 2, Cmd: 300, Type: 0}
}

// Pack encodes Attack struct to a byte array to be delivered over the command.
func (proto *Attack) Pack() []byte {
	bytes := make([]byte, 0)

	/* uint8 */
	typeBytes := make([]byte, 1)
	typeBytes[0] = proto.Type
	bytes = append(bytes, typeBytes...)

	// done
	return bytes
}

// Unpack decodes the command payload byte array to Attack struct.
func (proto *Attack) Unpack(bytes []byte) error {
	if len(bytes) < 1 {
		return errors.New("AttackUnpackError")
	}

	offset := 0

	/* uint8 */
	proto.Type = uint8(bytes[offset])
	offset++

	return nil
}

func (proto *Attack) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("Type = ", proto.Type))
	return strings.Join(list, " | ")
}

func (proto *Attack) GetVer() uint8 {
	return proto.Ver
}
func (proto *Attack) GetCmd() uint16 {
	return proto.Cmd
}
