// © 2019-2024 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// # Auto-generated by Diarkis Version 1.0.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements
package custom

import "encoding/binary"
import "errors"
import "fmt"
import "strings"

// AttackResultVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const AttackResultVer uint8 = 2

// AttackResultCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const AttackResultCmd uint16 = 300

// AttackResult represents the command protocol data structure.
type AttackResult struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd         uint16
	Damage      uint16
	TotalDamage uint16
	Type        uint8
	Uid         string
}

// NewAttackResult creates a new instance of AttackResult struct.
func NewAttackResult() *AttackResult {
	return &AttackResult{Ver: 2, Cmd: 300, Damage: 0, TotalDamage: 0, Type: 0, Uid: ""}
}

// Pack encodes AttackResult struct to a byte array to be delivered over the command.
func (proto *AttackResult) Pack() []byte {
	bytes := make([]byte, 0)

	/* uint16 */
	damageBytes := make([]byte, 2)
	binary.BigEndian.PutUint16(damageBytes, uint16(proto.Damage))
	bytes = append(bytes, damageBytes...)

	/* uint16 */
	totalDamageBytes := make([]byte, 2)
	binary.BigEndian.PutUint16(totalDamageBytes, uint16(proto.TotalDamage))
	bytes = append(bytes, totalDamageBytes...)

	/* uint8 */
	typeBytes := make([]byte, 1)
	typeBytes[0] = proto.Type
	bytes = append(bytes, typeBytes...)

	/* string */
	uidSizeBytes := make([]byte, 2)
	binary.BigEndian.PutUint16(uidSizeBytes, uint16(len(proto.Uid)))
	bytes = append(bytes, uidSizeBytes...)
	bytes = append(bytes, []byte(proto.Uid)...)

	// done
	return bytes
}

// Unpack decodes the command payload byte array to AttackResult struct.
func (proto *AttackResult) Unpack(bytes []byte) error {
	if len(bytes) < 7 {
		return errors.New("AttackResultUnpackError")
	}

	offset := 0

	/* uint16 */
	proto.Damage = binary.BigEndian.Uint16(bytes[offset : offset+2])
	offset += 2

	/* uint16 */
	proto.TotalDamage = binary.BigEndian.Uint16(bytes[offset : offset+2])
	offset += 2

	/* uint8 */
	proto.Type = uint8(bytes[offset])
	offset++

	/* string */
	uidSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if uidSize+offset > len(bytes) {
		return errors.New("UnpackError")
	}
	offset += 2
	proto.Uid = string(bytes[offset : offset+uidSize])
	offset += uidSize

	return nil
}

func (proto *AttackResult) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("Damage = ", proto.Damage))
	list = append(list, fmt.Sprint("TotalDamage = ", proto.TotalDamage))
	list = append(list, fmt.Sprint("Type = ", proto.Type))
	list = append(list, fmt.Sprint("Uid = ", proto.Uid))
	return strings.Join(list, " | ")
}

func (proto *AttackResult) GetVer() uint8 {
	return proto.Ver
}
func (proto *AttackResult) GetCmd() uint16 {
	return proto.Cmd
}
