// © 2019-2026 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Puffer v0.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package custom

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// DiarkisCharacterSyncPayload represents the command protocol data structure.
type DiarkisCharacterSyncPayload struct {
	Engine    uint8
	Frames    []*DiarkisCharacterFrameData
	Timestamp int64
}

// NewDiarkisCharacterSyncPayload creates a new instance of DiarkisCharacterSyncPayload struct.
func NewDiarkisCharacterSyncPayload() *DiarkisCharacterSyncPayload {
	return &DiarkisCharacterSyncPayload{}
}

// Pack encodes DiarkisCharacterSyncPayload struct to a byte array to be delivered over the command.
func (proto *DiarkisCharacterSyncPayload) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())
	bytes = append(bytes, proto.Engine)
	framesLengthBytes := make([]byte, 2)
	framesLength := len(proto.Frames)
	binary.BigEndian.PutUint16(framesLengthBytes, uint16(framesLength))
	bytes = append(bytes, framesLengthBytes...)
	for i := 0; i < framesLength; i++ {
		framesSizeBytes := make([]byte, 2)
		framesPacked := proto.Frames[i].Pack()
		binary.BigEndian.PutUint16(framesSizeBytes, uint16(len(framesPacked)))
		bytes = append(bytes, framesSizeBytes...)
		bytes = append(bytes, framesPacked...)
	}
	bytes = binary.BigEndian.AppendUint64(bytes, uint64(proto.Timestamp))
	return bytes
}

// Unpack decodes the command payload byte array to DiarkisCharacterSyncPayload struct.
func (proto *DiarkisCharacterSyncPayload) Unpack(bytes []byte) error {
	unpackErr := errors.New("DiarkisCharacterSyncPayloadUnpackError")
	if len(bytes) < 11 {
		return unpackErr
	}
	offset := 0
	if offset+1 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Engine: %w", unpackErr)
	}
	proto.Engine = uint8(bytes[offset])
	offset++
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Frames: %w", unpackErr)
	}
	framesLength := int(binary.BigEndian.Uint16((bytes[offset : offset+2])))
	offset += 2
	proto.Frames = make([]*DiarkisCharacterFrameData, framesLength)
	for i := 0; i < framesLength; i++ {
		if offset+2 > len(bytes) {
			return fmt.Errorf("payload too short to unpack Frames at index %d: %w", i, unpackErr)
		}
		framesSize := int(binary.BigEndian.Uint16((bytes[offset : offset+2])))
		offset += 2
		if framesSize+offset > len(bytes) {
			return fmt.Errorf("payload too short to unpack Frames at index %d: %w", i, unpackErr)
		}
		framesBytes := bytes[offset : offset+framesSize : offset+framesSize]
		item := &DiarkisCharacterFrameData{}
		if err := item.Unpack(framesBytes); err != nil {
			return fmt.Errorf("payload too short to unpack Frames at index %d: %w", i, err)
		}
		proto.Frames[i] = item
		offset += framesSize
	}
	if offset+8 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Timestamp: %w", unpackErr)
	}
	proto.Timestamp = int64(binary.BigEndian.Uint64(bytes[offset : offset+8]))
	offset += 8
	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *DiarkisCharacterSyncPayload) PackedSize() int {
	var packedSize = 0
	packedSize += 1
	packedSize += 2
	for _, v := range proto.Frames {
		packedSize += 2 + v.PackedSize()
	}
	packedSize += 8
	return packedSize
}

func (proto *DiarkisCharacterSyncPayload) String() string {
	var list []string
	list = append(list, fmt.Sprint("Engine = ", proto.Engine))
	for i, item := range proto.Frames {
		list = append(list, fmt.Sprint("Frames[", i, "] = ", "[", item.String(), "]"))
	}
	list = append(list, fmt.Sprint("Timestamp = ", proto.Timestamp))
	return strings.Join(list, " | ")
}
