// © 2019-2026 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Puffer v0.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package custom

import (
	"encoding/binary"
	"errors"
	"fmt"
	"math"
	"strings"
)

// DiarkisVector3 represents the command protocol data structure.
type DiarkisVector3 struct {
	X float32
	Y float32
	Z float32
}

// NewDiarkisVector3 creates a new instance of DiarkisVector3 struct.
func NewDiarkisVector3() *DiarkisVector3 {
	return &DiarkisVector3{}
}

// Pack encodes DiarkisVector3 struct to a byte array to be delivered over the command.
func (proto *DiarkisVector3) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())
	bytes = binary.BigEndian.AppendUint32(bytes, math.Float32bits(proto.X))
	bytes = binary.BigEndian.AppendUint32(bytes, math.Float32bits(proto.Y))
	bytes = binary.BigEndian.AppendUint32(bytes, math.Float32bits(proto.Z))
	return bytes
}

// Unpack decodes the command payload byte array to DiarkisVector3 struct.
func (proto *DiarkisVector3) Unpack(bytes []byte) error {
	unpackErr := errors.New("DiarkisVector3UnpackError")
	if len(bytes) < 12 {
		return unpackErr
	}
	offset := 0
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack X: %w", unpackErr)
	}
	xBits := binary.BigEndian.Uint32(bytes[offset : offset+4])
	offset += 4
	proto.X = math.Float32frombits(xBits)
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Y: %w", unpackErr)
	}
	yBits := binary.BigEndian.Uint32(bytes[offset : offset+4])
	offset += 4
	proto.Y = math.Float32frombits(yBits)
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Z: %w", unpackErr)
	}
	zBits := binary.BigEndian.Uint32(bytes[offset : offset+4])
	offset += 4
	proto.Z = math.Float32frombits(zBits)
	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *DiarkisVector3) PackedSize() int {
	var packedSize = 0
	packedSize += 4
	packedSize += 4
	packedSize += 4
	return packedSize
}

func (proto *DiarkisVector3) String() string {
	var list []string
	list = append(list, fmt.Sprint("X = ", proto.X))
	list = append(list, fmt.Sprint("Y = ", proto.Y))
	list = append(list, fmt.Sprint("Z = ", proto.Z))
	return strings.Join(list, " | ")
}
