// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Puffer v0.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package custom

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// DiarkisCharacterFrameData represents the command protocol data structure.
type DiarkisCharacterFrameData struct {
	AnimationBlend    uint8
	AnimationID       uint8
	Position          *DiarkisVector3
	RotationAngles    uint16
	TimestampInterval uint16
}

// NewDiarkisCharacterFrameData creates a new instance of DiarkisCharacterFrameData struct.
func NewDiarkisCharacterFrameData() *DiarkisCharacterFrameData {
	return &DiarkisCharacterFrameData{}
}

// Pack encodes DiarkisCharacterFrameData struct to a byte array to be delivered over the command.
func (proto *DiarkisCharacterFrameData) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())
	bytes = append(bytes, proto.AnimationBlend)
	bytes = append(bytes, proto.AnimationID)
	positionSizeBytes := make([]byte, 2)
	positionPacked := proto.Position.Pack()
	binary.BigEndian.PutUint16(positionSizeBytes, uint16(len(positionPacked)))
	bytes = append(bytes, positionSizeBytes...)
	bytes = append(bytes, positionPacked...)
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(proto.RotationAngles))
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(proto.TimestampInterval))
	return bytes
}

// Unpack decodes the command payload byte array to DiarkisCharacterFrameData struct.
func (proto *DiarkisCharacterFrameData) Unpack(bytes []byte) error {
	unpackErr := errors.New("DiarkisCharacterFrameDataUnpackError")
	if len(bytes) < 8 {
		return unpackErr
	}
	offset := 0
	if offset+1 > len(bytes) {
		return fmt.Errorf("payload too short to unpack AnimationBlend: %w", unpackErr)
	}
	proto.AnimationBlend = uint8(bytes[offset])
	offset++
	if offset+1 > len(bytes) {
		return fmt.Errorf("payload too short to unpack AnimationID: %w", unpackErr)
	}
	proto.AnimationID = uint8(bytes[offset])
	offset++
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Position: %w", unpackErr)
	}
	positionSizeBytes := int(binary.BigEndian.Uint16((bytes[offset : offset+2])))
	offset += 2
	if positionSizeBytes+offset > len(bytes) {
		return fmt.Errorf("payload too short to unpack Position: %w", unpackErr)
	}
	positionBytes := bytes[offset : offset+positionSizeBytes : offset+positionSizeBytes]
	proto.Position = &DiarkisVector3{}
	if err := proto.Position.Unpack(positionBytes); err != nil {
		return fmt.Errorf("failed to unpack Position: %w", err)
	}
	offset += positionSizeBytes
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack RotationAngles: %w", unpackErr)
	}
	proto.RotationAngles = binary.BigEndian.Uint16(bytes[offset : offset+2])
	offset += 2
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack TimestampInterval: %w", unpackErr)
	}
	proto.TimestampInterval = binary.BigEndian.Uint16(bytes[offset : offset+2])
	offset += 2
	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *DiarkisCharacterFrameData) PackedSize() int {
	var packedSize = 0
	packedSize += 1
	packedSize += 1
	packedSize += proto.Position.PackedSize()
	packedSize += 2
	packedSize += 2
	return packedSize
}

func (proto *DiarkisCharacterFrameData) String() string {
	var list []string
	list = append(list, fmt.Sprint("AnimationBlend = ", proto.AnimationBlend))
	list = append(list, fmt.Sprint("AnimationID = ", proto.AnimationID))
	list = append(list, fmt.Sprint("Position = ", proto.Position.String()))
	list = append(list, fmt.Sprint("RotationAngles = ", proto.RotationAngles))
	list = append(list, fmt.Sprint("TimestampInterval = ", proto.TimestampInterval))
	return strings.Join(list, " | ")
}
