// © 2019-2026 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Puffer v0.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package custom

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// EchoVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const EchoVer uint8 = 2

// EchoCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const EchoCmd uint16 = 200

// Echo represents the command protocol data structure.
type Echo struct {
	Message string
}

// NewEcho creates a new instance of Echo struct.
func NewEcho() *Echo {
	return &Echo{}
}

// Pack encodes Echo struct to a byte array to be delivered over the command.
func (proto *Echo) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.Message)))
	bytes = append(bytes, []byte(proto.Message)...)
	return bytes
}

// Unpack decodes the command payload byte array to Echo struct.
func (proto *Echo) Unpack(bytes []byte) error {
	unpackErr := errors.New("EchoUnpackError")
	if len(bytes) < 2 {
		return unpackErr
	}
	offset := 0
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Message: %w", unpackErr)
	}
	messageSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if messageSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Message: %w", unpackErr)
	}
	offset += 2
	proto.Message = string(bytes[offset : offset+messageSize : offset+messageSize])
	offset += messageSize
	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *Echo) PackedSize() int {
	var packedSize = 0
	packedSize += 2 + len(proto.Message)
	return packedSize
}

func (proto *Echo) String() string {
	var list []string
	list = append(list, fmt.Sprint("Message = ", proto.Message))
	return strings.Join(list, " | ")
}

// Ver returns the protocol's command version.
func (proto *Echo) Ver() uint8 {
	return EchoVer
}

// Cmd returns the protocol's command ID.
func (proto *Echo) Cmd() uint16 {
	return EchoCmd
}
