// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package custom

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// GetFieldInfoVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const GetFieldInfoVer uint8 = 2

// GetFieldInfoCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const GetFieldInfoCmd uint16 = 4001

// GetFieldInfo represents the command protocol data structure.
type GetFieldInfo struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd               uint16
	FieldOfVisionSize int64
	FieldSize         int64
	NodeCount         int32
}

// NewGetFieldInfo creates a new instance of GetFieldInfo struct.
func NewGetFieldInfo() *GetFieldInfo {
	return &GetFieldInfo{Ver: 2, Cmd: 4001, FieldOfVisionSize: 0, FieldSize: 0, NodeCount: 0}
}

// Pack encodes GetFieldInfo struct to a byte array to be delivered over the command.
func (proto *GetFieldInfo) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	/* int64 */
	bytes = binary.BigEndian.AppendUint64(bytes, uint64(proto.FieldOfVisionSize))

	/* int64 */
	bytes = binary.BigEndian.AppendUint64(bytes, uint64(proto.FieldSize))

	/* int32 */
	bytes = binary.BigEndian.AppendUint32(bytes, uint32(proto.NodeCount))

	// done
	return bytes
}

// Unpack decodes the command payload byte array to GetFieldInfo struct.
func (proto *GetFieldInfo) Unpack(bytes []byte) error {
	unpackErr := errors.New("GetFieldInfoUnpackError")
	if len(bytes) < 20 {
		return unpackErr
	}

	offset := 0

	/* int64 */
	if offset+8 > len(bytes) {
		return fmt.Errorf("payload too short to unpack FieldOfVisionSize: %w", unpackErr)
	}
	proto.FieldOfVisionSize = int64(binary.BigEndian.Uint64(bytes[offset : offset+8]))
	offset += 8

	/* int64 */
	if offset+8 > len(bytes) {
		return fmt.Errorf("payload too short to unpack FieldSize: %w", unpackErr)
	}
	proto.FieldSize = int64(binary.BigEndian.Uint64(bytes[offset : offset+8]))
	offset += 8

	/* int32 */
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack NodeCount: %w", unpackErr)
	}
	proto.NodeCount = int32(binary.BigEndian.Uint32(bytes[offset : offset+4]))
	offset += 4

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *GetFieldInfo) PackedSize() int {
	var packedSize = 0
	packedSize += 8 // FieldOfVisionSize
	packedSize += 8 // FieldSize
	packedSize += 4 // NodeCount
	return packedSize
}

func (proto *GetFieldInfo) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("FieldOfVisionSize = ", proto.FieldOfVisionSize))
	list = append(list, fmt.Sprint("FieldSize = ", proto.FieldSize))
	list = append(list, fmt.Sprint("NodeCount = ", proto.NodeCount))
	return strings.Join(list, " | ")
}

func (proto *GetFieldInfo) GetVer() uint8 {
	return proto.Ver
}
func (proto *GetFieldInfo) GetCmd() uint16 {
	return proto.Cmd
}
