apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mars
spec:
  serviceName: "mars"
  replicas: 1
  selector:
    matchLabels:
      component: mars
  template:
    metadata:
      labels:
        component: mars
    spec:
      containers:
        - name: mars
          image: mars
          imagePullPolicy: Always
          ports:
            - containerPort: 6779
              name: mars
          volumeMounts:
            - name: mars-conf
              mountPath: /bin/mars
            - name: hc-conf
              mountPath: /bin/tools/configs
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: diarkis-private
      tolerations:
        - key: "diarkis.io/network"
          operator: "Equal"
          value: "private"
          effect: "NoExecute"
      volumes:
        - name: mars-conf
          configMap:
            name: mars-conf
        - name: hc-conf
          configMap:
            name: hc-conf
