// Code generated by Diarkis Puffer module: DO NOT EDIT
//
// Generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Diarkis.Core.Client;

namespace Diarkis.CustomCommands {

// Broadcast the LoD data to the room. Synchronize data more frequently with nearby characters, and less frequently with distant characters.
public class BroadcastLoD : DiarkisPufferObject
{
	public static byte VER {
		get => 2;
	}
	public static ushort CMD {
		get => 1001;
	}

	// Data for synchronization
	public byte[] Payload = new byte[0];
	// The x coordinate of the local character
	public int X = 0;
	// The y coordinate of the local character
	public int Y = 0;

	public override int GetRequiredBufferSize()
	{
		int len = 0;
		len += sizeof(ushort);
		len += sizeof(byte) * Payload.Length;
		len += sizeof(int);
		len += sizeof(int);
		len += 0; // packed boolean size
		return len;
	}

	public override int Serialize(ref byte[] buffer, int index)
	{
		int idx = index;
		
				/* byte[] */
		idx += DiarkisSerialization.Serialize(Payload, ref buffer, idx);

		/* int */
		idx += DiarkisSerialization.Serialize(X, ref buffer, idx);

		/* int */
		idx += DiarkisSerialization.Serialize(Y, ref buffer, idx);

		return idx - index;
	}

	public void Pack(ref byte[] buffer)
	{
		this.Serialize(ref buffer, 0);
	}

	public byte[] Pack()
	{
		byte[] buffer = new byte[this.GetRequiredBufferSize()];
		this.Serialize(ref buffer, 0);
		// done
		return buffer;
	}

	public bool Unpack(Span<byte> bytes)
	{
		
		int offset = 0;

		/* byte[] */
		Span<byte> payloadSizeBytes = bytes.Slice(offset, 2);
		int payloadSize = (int)((payloadSizeBytes[0] << 8) | payloadSizeBytes[1]);
		if (payloadSize + offset > bytes.Length)
		{
			return false;
		}
		offset += 2;
		Payload = bytes.Slice(offset, payloadSize).ToArray();
		offset += payloadSize;

		/* int */
		Span<byte> xBytes = bytes.Slice(offset, 4);
		X = (int)((xBytes[0] << 24) | (xBytes[1] << 16) | (xBytes[2] << 8) | xBytes[3]);
		offset += 4;

		/* int */
		Span<byte> yBytes = bytes.Slice(offset, 4);
		Y = (int)((yBytes[0] << 24) | (yBytes[1] << 16) | (yBytes[2] << 8) | yBytes[3]);
		offset += 4;


		return true;
	}

	public bool Unpack(byte[] bytes)
	{
		if (bytes.Length < 10)
		{
			return false;
		}
		return Unpack(new Span<byte>(bytes));
	}

	public override string ToString()
	{
		List<string> list = new List<string>();
		list.Add(string.Format("Payload = [{0}]", string.Join(" ", Payload)));
		list.Add(string.Format("X = {0}", X));
		list.Add(string.Format("Y = {0}", Y));
		return string.Join(" | ", list);
	}
}

}
