// Code generated by Diarkis Puffer module: DO NOT EDIT
//
// Auto-generated by Diarkis Puffer v0.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Buffers.Binary;
using Diarkis.Core.Client;

namespace Diarkis.CustomCommands {


// Push the LoD data to the client.
public class BroadcastLoDPush : DiarkisPufferObject
{
	/// <summary>
	/// Static version of ver()
	/// </summary>
	public static byte VER { get => 2; }
	
	/// <summary>
	/// Static version of cmd()
	/// </summary>
	public static ushort CMD { get => 1001; }

	public override byte ver() {
		return VER;
	}
	public override ushort cmd() {
		return CMD;
	}

	// Data for synchronization
	public byte[] Payload = new byte[0];

	public override int GetRequiredBufferSize()
	{
		int len = 0;
		len += sizeof(ushort);
		len += sizeof(byte) * Payload.Length;
		return len;
	}

	public override int Serialize(ref byte[] buffer, int index)
	{
		int idx = index;
		idx += DiarkisSerialization.Serialize(Payload, ref buffer, idx);
		return idx - index;
	}

	public override bool Unpack(ReadOnlySpan<byte> bytes)
	{
		int offset = 0;
		if (offset + 2 > bytes.Length) return false;
		int payloadSize = BinaryPrimitives.ReadUInt16BigEndian(bytes.Slice(offset, 2));
		offset += 2;
		if (payloadSize + offset > bytes.Length) return false;
		Payload = bytes.Slice(offset, payloadSize).ToArray();
		offset += payloadSize;
		return true;
	}

	public override bool Unpack(byte[] bytes)
	{
		if (bytes.Length < 2)
		{
			return false;
		}
		return Unpack(new ReadOnlySpan<byte>(bytes));
	}

	public override string ToString()
	{
		List<string> list = new List<string>();
		list.Add(string.Format("Payload = [{0}]", string.Join(" ", Payload)));
		return string.Join(" | ", list);
	}
}

}
