// Code generated by Diarkis Puffer module: DO NOT EDIT
//
// Generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Diarkis.Core.Client;

namespace Diarkis.CustomCommands {

// Push the LoD data to the client.
public class BroadcastLoDPush : DiarkisPufferObject
{
	public static byte VER {
		get => 2;
	}
	public static ushort CMD {
		get => 1001;
	}

	// Data for synchronization
	public byte[] Payload = new byte[0];

	public override int GetRequiredBufferSize()
	{
		int len = 0;
		len += sizeof(ushort);
		len += sizeof(byte) * Payload.Length;
		len += 0; // packed boolean size
		return len;
	}

	public override int Serialize(ref byte[] buffer, int index)
	{
		int idx = index;
		
				/* byte[] */
		idx += DiarkisSerialization.Serialize(Payload, ref buffer, idx);

		return idx - index;
	}

	public void Pack(ref byte[] buffer)
	{
		this.Serialize(ref buffer, 0);
	}

	public byte[] Pack()
	{
		byte[] buffer = new byte[this.GetRequiredBufferSize()];
		this.Serialize(ref buffer, 0);
		// done
		return buffer;
	}

	public bool Unpack(Span<byte> bytes)
	{
		
		int offset = 0;

		/* byte[] */
		Span<byte> payloadSizeBytes = bytes.Slice(offset, 2);
		int payloadSize = (int)((payloadSizeBytes[0] << 8) | payloadSizeBytes[1]);
		if (payloadSize + offset > bytes.Length)
		{
			return false;
		}
		offset += 2;
		Payload = bytes.Slice(offset, payloadSize).ToArray();
		offset += payloadSize;


		return true;
	}

	public bool Unpack(byte[] bytes)
	{
		if (bytes.Length < 2)
		{
			return false;
		}
		return Unpack(new Span<byte>(bytes));
	}

	public override string ToString()
	{
		List<string> list = new List<string>();
		list.Add(string.Format("Payload = [{0}]", string.Join(" ", Payload)));
		return string.Join(" | ", list);
	}
}

}
