// Code generated by Diarkis Puffer module: DO NOT EDIT
//
// Generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Diarkis.Core.Client;

namespace Diarkis.CustomCommands {

// Get the LoD information of the room.
public class GetLoDInfo : DiarkisPufferObject
{
	public static byte VER {
		get => 2;
	}
	public static ushort CMD {
		get => 1002;
	}



	public override int GetRequiredBufferSize()
	{
		int len = 0;
		len += 0; // packed boolean size
		return len;
	}

	public override int Serialize(ref byte[] buffer, int index)
	{
		int idx = index;
		
		
		return idx - index;
	}

	public void Pack(ref byte[] buffer)
	{
		this.Serialize(ref buffer, 0);
	}

	public byte[] Pack()
	{
		byte[] buffer = new byte[this.GetRequiredBufferSize()];
		this.Serialize(ref buffer, 0);
		// done
		return buffer;
	}

	public bool Unpack(Span<byte> bytes)
	{
		
		return true;
	}

	public bool Unpack(byte[] bytes)
	{
		if (bytes.Length < 0)
		{
			return false;
		}
		return Unpack(new Span<byte>(bytes));
	}

	public override string ToString()
	{
		List<string> list = new List<string>();

		return string.Join(" | ", list);
	}
}

}
