// Code generated by Diarkis Puffer module: DO NOT EDIT
//
// Auto-generated by Diarkis Puffer v0.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Buffers.Binary;
using Diarkis.Core.Client;

namespace Diarkis.CustomCommands {


// Get the LoD information of the room.
public class GetLoDInfo : DiarkisPufferObject
{
	/// <summary>
	/// Static version of ver()
	/// </summary>
	public static byte VER { get => 2; }
	
	/// <summary>
	/// Static version of cmd()
	/// </summary>
	public static ushort CMD { get => 1002; }

	public override byte ver() {
		return VER;
	}
	public override ushort cmd() {
		return CMD;
	}

	public override int GetRequiredBufferSize()
	{
		int len = 0;
		return len;
	}

	public override int Serialize(ref byte[] buffer, int index)
	{
		int idx = index;
		return idx - index;
	}

	public override bool Unpack(ReadOnlySpan<byte> bytes)
	{
		return true;
	}

	public override bool Unpack(byte[] bytes)
	{
		if (bytes.Length < 0)
		{
			return false;
		}
		return Unpack(new ReadOnlySpan<byte>(bytes));
	}

	public override string ToString()
	{
		return string.Empty;
	}
}

}
