// Code generated by Diarkis Puffer module: DO NOT EDIT
//
// Generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Diarkis.Core.Client;

namespace Diarkis.CustomCommands {

// Response the LoD information of the room.
public class GetLoDInfoResponse : DiarkisPufferObject
{
	public static byte VER {
		get => 2;
	}
	public static ushort CMD {
		get => 1002;
	}

	// The maximum distance for far characters (centimeters)
	public int MaxDistanceForFar = 0;
	// The maximum distance for nearby characters (centimeters)
	public int MaxDistanceForNearby = 0;
	// Synchronization interval for far characters (milliseconds)
	public int SyncIntervalForFar = 0;
	// Synchronization interval for nearby characters (milliseconds)
	public int SyncIntervalForNearby = 0;

	public override int GetRequiredBufferSize()
	{
		int len = 0;
		len += sizeof(int);
		len += sizeof(int);
		len += sizeof(int);
		len += sizeof(int);
		len += 0; // packed boolean size
		return len;
	}

	public override int Serialize(ref byte[] buffer, int index)
	{
		int idx = index;
		
				/* int */
		idx += DiarkisSerialization.Serialize(MaxDistanceForFar, ref buffer, idx);

		/* int */
		idx += DiarkisSerialization.Serialize(MaxDistanceForNearby, ref buffer, idx);

		/* int */
		idx += DiarkisSerialization.Serialize(SyncIntervalForFar, ref buffer, idx);

		/* int */
		idx += DiarkisSerialization.Serialize(SyncIntervalForNearby, ref buffer, idx);

		return idx - index;
	}

	public void Pack(ref byte[] buffer)
	{
		this.Serialize(ref buffer, 0);
	}

	public byte[] Pack()
	{
		byte[] buffer = new byte[this.GetRequiredBufferSize()];
		this.Serialize(ref buffer, 0);
		// done
		return buffer;
	}

	public bool Unpack(Span<byte> bytes)
	{
		
		int offset = 0;

		/* int */
		Span<byte> maxDistanceForFarBytes = bytes.Slice(offset, 4);
		MaxDistanceForFar = (int)((maxDistanceForFarBytes[0] << 24) | (maxDistanceForFarBytes[1] << 16) | (maxDistanceForFarBytes[2] << 8) | maxDistanceForFarBytes[3]);
		offset += 4;

		/* int */
		Span<byte> maxDistanceForNearbyBytes = bytes.Slice(offset, 4);
		MaxDistanceForNearby = (int)((maxDistanceForNearbyBytes[0] << 24) | (maxDistanceForNearbyBytes[1] << 16) | (maxDistanceForNearbyBytes[2] << 8) | maxDistanceForNearbyBytes[3]);
		offset += 4;

		/* int */
		Span<byte> syncIntervalForFarBytes = bytes.Slice(offset, 4);
		SyncIntervalForFar = (int)((syncIntervalForFarBytes[0] << 24) | (syncIntervalForFarBytes[1] << 16) | (syncIntervalForFarBytes[2] << 8) | syncIntervalForFarBytes[3]);
		offset += 4;

		/* int */
		Span<byte> syncIntervalForNearbyBytes = bytes.Slice(offset, 4);
		SyncIntervalForNearby = (int)((syncIntervalForNearbyBytes[0] << 24) | (syncIntervalForNearbyBytes[1] << 16) | (syncIntervalForNearbyBytes[2] << 8) | syncIntervalForNearbyBytes[3]);
		offset += 4;


		return true;
	}

	public bool Unpack(byte[] bytes)
	{
		if (bytes.Length < 16)
		{
			return false;
		}
		return Unpack(new Span<byte>(bytes));
	}

	public override string ToString()
	{
		List<string> list = new List<string>();
		list.Add(string.Format("MaxDistanceForFar = {0}", MaxDistanceForFar));
		list.Add(string.Format("MaxDistanceForNearby = {0}", MaxDistanceForNearby));
		list.Add(string.Format("SyncIntervalForFar = {0}", SyncIntervalForFar));
		list.Add(string.Format("SyncIntervalForNearby = {0}", SyncIntervalForNearby));
		return string.Join(" | ", list);
	}
}

}
