// Code generated by Diarkis Puffer module: DO NOT EDIT
//
// Auto-generated by Diarkis Puffer v0.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Buffers.Binary;
using Diarkis.Core.Client;

namespace Diarkis.CustomCommands {


// Response the LoD information of the room.
public class GetLoDInfoResponse : DiarkisPufferObject
{
	/// <summary>
	/// Static version of ver()
	/// </summary>
	public static byte VER { get => 2; }
	
	/// <summary>
	/// Static version of cmd()
	/// </summary>
	public static ushort CMD { get => 1002; }

	public override byte ver() {
		return VER;
	}
	public override ushort cmd() {
		return CMD;
	}

	// The maximum distance for far characters (centimeters)
	public int MaxDistanceForFar = 0;
	// The maximum distance for nearby characters (centimeters)
	public int MaxDistanceForNearby = 0;
	// Synchronization interval for far characters (milliseconds)
	public int SyncIntervalForFar = 0;
	// Synchronization interval for nearby characters (milliseconds)
	public int SyncIntervalForNearby = 0;

	public override int GetRequiredBufferSize()
	{
		int len = 0;
		len += sizeof(int);
		len += sizeof(int);
		len += sizeof(int);
		len += sizeof(int);
		return len;
	}

	public override int Serialize(ref byte[] buffer, int index)
	{
		int idx = index;
		idx += DiarkisSerialization.Serialize(MaxDistanceForFar, ref buffer, idx);
		idx += DiarkisSerialization.Serialize(MaxDistanceForNearby, ref buffer, idx);
		idx += DiarkisSerialization.Serialize(SyncIntervalForFar, ref buffer, idx);
		idx += DiarkisSerialization.Serialize(SyncIntervalForNearby, ref buffer, idx);
		return idx - index;
	}

	public override bool Unpack(ReadOnlySpan<byte> bytes)
	{
		int offset = 0;
		if (offset + 4 > bytes.Length) return false;
		MaxDistanceForFar = BinaryPrimitives.ReadInt32BigEndian(bytes.Slice(offset, 4));
		offset += 4;
		if (offset + 4 > bytes.Length) return false;
		MaxDistanceForNearby = BinaryPrimitives.ReadInt32BigEndian(bytes.Slice(offset, 4));
		offset += 4;
		if (offset + 4 > bytes.Length) return false;
		SyncIntervalForFar = BinaryPrimitives.ReadInt32BigEndian(bytes.Slice(offset, 4));
		offset += 4;
		if (offset + 4 > bytes.Length) return false;
		SyncIntervalForNearby = BinaryPrimitives.ReadInt32BigEndian(bytes.Slice(offset, 4));
		offset += 4;
		return true;
	}

	public override bool Unpack(byte[] bytes)
	{
		if (bytes.Length < 16)
		{
			return false;
		}
		return Unpack(new ReadOnlySpan<byte>(bytes));
	}

	public override string ToString()
	{
		List<string> list = new List<string>();
		list.Add(string.Format("MaxDistanceForFar = {0}", MaxDistanceForFar));
		list.Add(string.Format("MaxDistanceForNearby = {0}", MaxDistanceForNearby));
		list.Add(string.Format("SyncIntervalForFar = {0}", SyncIntervalForFar));
		list.Add(string.Format("SyncIntervalForNearby = {0}", SyncIntervalForNearby));
		return string.Join(" | ", list);
	}
}

}
