apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dgs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dgs
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metric:
          name: dgs_online_dgs_node
        target:
          type: Value
          value: "3"
