apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev0
resources:
  - ../../base
  - ./shared/secrets/dockerhub-secrets.yaml

# build target
patches:
  - path: http/deploy.yaml
  - path: udp/deploy.yaml
  - path: tcp/deploy.yaml

configMapGenerator:
  - name: shared-conf
    behavior: replace
    files:
      - shared/conf/field.json
      - shared/conf/dm.json
      - shared/conf/group.json
      - shared/conf/log.json
      - shared/conf/matching.json
      - shared/conf/mesh.json
      - shared/conf/dive.json

  - name: http-conf
    behavior: replace
    files:
      - http/conf/main.json

  - name: udp-conf
    behavior: replace
    files:
      - udp/conf/main.json

  - name: tcp-conf
    behavior: replace
    files:
      - tcp/conf/main.json

images:
  - name: udp
    newName: __YOUR_DOCKERHUB_REPOSITORY_NAME__/udp
    newTag: latest
  - name: tcp
    newName: __YOUR_DOCKERHUB_REPOSITORY_NAME__/tcp
    newTag: latest
  - name: mars
    newName: __YOUR_DOCKERHUB_REPOSITORY_NAME__/mars
    newTag: latest
  - name: http
    newName: __YOUR_DOCKERHUB_REPOSITORY_NAME__/http
    newTag: latest
