// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package dgs

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// InstanceCreatePushVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const InstanceCreatePushVer uint8 = 2

// InstanceCreatePushCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const InstanceCreatePushCmd uint16 = 50000

// InstanceCreatePush represents the command protocol data structure.
type InstanceCreatePush struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd uint16
	// IV of remote DGS user.
	IV []byte
	// Key of remote DGS user.
	Key []byte
	// MacKey of remote DGS user.
	MacKey []byte
	// SID of remote DGS user.
	SID []byte
	// Host of remote DGS.
	ServerHost string
	// Port of remote DGS.
	ServerPort uint16
	// Server type of remote DGS.
	ServerType string
	// DGS allocation success value.
	Success bool
}

// NewInstanceCreatePush creates a new instance of InstanceCreatePush struct.
func NewInstanceCreatePush() *InstanceCreatePush {
	return &InstanceCreatePush{Ver: 2, Cmd: 50000, IV: make([]byte, 0), Key: make([]byte, 0), MacKey: make([]byte, 0), SID: make([]byte, 0), ServerHost: "", ServerPort: 0, ServerType: "", Success: false}
}

// Pack encodes InstanceCreatePush struct to a byte array to be delivered over the command.
func (proto *InstanceCreatePush) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	var _packedBooleanBytes [1]byte
	_ = _packedBooleanBytes
	if proto.Success {
		_packedBooleanBytes[0] |= (1 << 0)
	}
	/* uint8 */
	bytes = append(bytes, _packedBooleanBytes[0])
	/* []byte */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.IV)))
	bytes = append(bytes, proto.IV...)

	/* []byte */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.Key)))
	bytes = append(bytes, proto.Key...)

	/* []byte */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.MacKey)))
	bytes = append(bytes, proto.MacKey...)

	/* []byte */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.SID)))
	bytes = append(bytes, proto.SID...)

	/* string */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.ServerHost)))
	bytes = append(bytes, []byte(proto.ServerHost)...)

	/* uint16 */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(proto.ServerPort))

	/* string */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.ServerType)))
	bytes = append(bytes, []byte(proto.ServerType)...)

	// done
	return bytes
}

// Unpack decodes the command payload byte array to InstanceCreatePush struct.
func (proto *InstanceCreatePush) Unpack(bytes []byte) error {
	unpackErr := errors.New("InstanceCreatePushUnpackError")
	if len(bytes) < 15 {
		return unpackErr
	}

	offset := 0

	proto.Success = (uint8(bytes[offset+0]) & (1 << 0)) != 0
	offset += 1

	/* []byte */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack IV: %w", unpackErr)
	}
	iVSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if iVSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack IV: %w", unpackErr)
	}
	offset += 2
	proto.IV = make([]byte, iVSize)
	copy(proto.IV, bytes[offset:offset+iVSize:offset+iVSize])
	offset += iVSize

	/* []byte */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Key: %w", unpackErr)
	}
	keySize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if keySize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Key: %w", unpackErr)
	}
	offset += 2
	proto.Key = make([]byte, keySize)
	copy(proto.Key, bytes[offset:offset+keySize:offset+keySize])
	offset += keySize

	/* []byte */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack MacKey: %w", unpackErr)
	}
	macKeySize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if macKeySize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack MacKey: %w", unpackErr)
	}
	offset += 2
	proto.MacKey = make([]byte, macKeySize)
	copy(proto.MacKey, bytes[offset:offset+macKeySize:offset+macKeySize])
	offset += macKeySize

	/* []byte */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack SID: %w", unpackErr)
	}
	sIDSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if sIDSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack SID: %w", unpackErr)
	}
	offset += 2
	proto.SID = make([]byte, sIDSize)
	copy(proto.SID, bytes[offset:offset+sIDSize:offset+sIDSize])
	offset += sIDSize

	/* string */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack ServerHost: %w", unpackErr)
	}
	serverHostSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if serverHostSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack ServerHost: %w", unpackErr)
	}
	offset += 2
	proto.ServerHost = string(bytes[offset : offset+serverHostSize : offset+serverHostSize])
	offset += serverHostSize

	/* uint16 */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack ServerPort: %w", unpackErr)
	}
	proto.ServerPort = binary.BigEndian.Uint16(bytes[offset : offset+2])
	offset += 2

	/* string */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack ServerType: %w", unpackErr)
	}
	serverTypeSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if serverTypeSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack ServerType: %w", unpackErr)
	}
	offset += 2
	proto.ServerType = string(bytes[offset : offset+serverTypeSize : offset+serverTypeSize])
	offset += serverTypeSize

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *InstanceCreatePush) PackedSize() int {
	var packedSize = 0
	packedSize += 2 + len(proto.IV)         // IV
	packedSize += 2 + len(proto.Key)        // Key
	packedSize += 2 + len(proto.MacKey)     // MacKey
	packedSize += 2 + len(proto.SID)        // SID
	packedSize += 2 + len(proto.ServerHost) // ServerHost
	packedSize += 2                         // ServerPort
	packedSize += 2 + len(proto.ServerType) // ServerType
	packedSize += 1                         // packed booleans length
	return packedSize
}

func (proto *InstanceCreatePush) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("IV = ", proto.IV))
	list = append(list, fmt.Sprint("Key = ", proto.Key))
	list = append(list, fmt.Sprint("MacKey = ", proto.MacKey))
	list = append(list, fmt.Sprint("SID = ", proto.SID))
	list = append(list, fmt.Sprint("ServerHost = ", proto.ServerHost))
	list = append(list, fmt.Sprint("ServerPort = ", proto.ServerPort))
	list = append(list, fmt.Sprint("ServerType = ", proto.ServerType))
	list = append(list, fmt.Sprint("Success = ", proto.Success))
	return strings.Join(list, " | ")
}

func (proto *InstanceCreatePush) GetVer() uint8 {
	return proto.Ver
}
func (proto *InstanceCreatePush) GetCmd() uint16 {
	return proto.Cmd
}
