// © 2019-2025 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package dgs

import (
	"errors"
	"fmt"
	"strings"
)

// InstanceCreateResponseVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const InstanceCreateResponseVer uint8 = 2

// InstanceCreateResponseCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const InstanceCreateResponseCmd uint16 = 50000

// InstanceCreateResponse represents the command protocol data structure.
// DGS instance create response.
// The status possible values are:
//   - 0 success (created)
//   - 1 DGS is already starting. A previous call to instance create have been done and it is still ongoing.
//     The caller is part of the DGS creation members request.
//   - 2 DGS is already started. Client should either call backfill or the owner should call clear association.
//   - 3 DGS is starting and the caller is not part of the DGS creation members request.
//     Caller will not receive a credentials push but will receive InstanceAllocatedPush
//     with IsMember=false when the creation will be finished. Caller should call backfill
//     once this push event is received.
type InstanceCreateResponse struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd uint16
	// DGS creation status.
	Status uint8
}

// NewInstanceCreateResponse creates a new instance of InstanceCreateResponse struct.
func NewInstanceCreateResponse() *InstanceCreateResponse {
	return &InstanceCreateResponse{Ver: 2, Cmd: 50000, Status: 0}
}

// Pack encodes InstanceCreateResponse struct to a byte array to be delivered over the command.
func (proto *InstanceCreateResponse) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	/* uint8 */
	bytes = append(bytes, proto.Status)

	// done
	return bytes
}

// Unpack decodes the command payload byte array to InstanceCreateResponse struct.
func (proto *InstanceCreateResponse) Unpack(bytes []byte) error {
	unpackErr := errors.New("InstanceCreateResponseUnpackError")
	if len(bytes) < 1 {
		return unpackErr
	}

	offset := 0

	/* uint8 */
	if offset+1 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Status: %w", unpackErr)
	}
	proto.Status = uint8(bytes[offset])
	offset++

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *InstanceCreateResponse) PackedSize() int {
	var packedSize = 0
	packedSize += 1 // Status
	return packedSize
}

func (proto *InstanceCreateResponse) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("Status = ", proto.Status))
	return strings.Join(list, " | ")
}

func (proto *InstanceCreateResponse) GetVer() uint8 {
	return proto.Ver
}
func (proto *InstanceCreateResponse) GetCmd() uint16 {
	return proto.Cmd
}
