// © 2019-2025 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package dgs

import (
	"errors"
	"strings"
)

// InstanceCreateRequestVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const InstanceCreateRequestVer uint8 = 2

// InstanceCreateRequestCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const InstanceCreateRequestCmd uint16 = 50000

// InstanceCreateRequest represents the command protocol data structure.
type InstanceCreateRequest struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd uint16
}

// NewInstanceCreateRequest creates a new instance of InstanceCreateRequest struct.
func NewInstanceCreateRequest() *InstanceCreateRequest {
	return &InstanceCreateRequest{Ver: 2, Cmd: 50000}
}

// Pack encodes InstanceCreateRequest struct to a byte array to be delivered over the command.
func (proto *InstanceCreateRequest) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	// done
	return bytes
}

// Unpack decodes the command payload byte array to InstanceCreateRequest struct.
func (proto *InstanceCreateRequest) Unpack(bytes []byte) error {
	unpackErr := errors.New("InstanceCreateRequestUnpackError")
	if len(bytes) < 0 {
		return unpackErr
	}

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *InstanceCreateRequest) PackedSize() int {
	var packedSize = 0
	return packedSize
}

func (proto *InstanceCreateRequest) String() string {
	list := make([]string, 0)

	return strings.Join(list, " | ")
}

func (proto *InstanceCreateRequest) GetVer() uint8 {
	return proto.Ver
}
func (proto *InstanceCreateRequest) GetCmd() uint16 {
	return proto.Cmd
}
