// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package dgs

import (
	"errors"
	"strings"
)

// InstanceBackfillRequestVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const InstanceBackfillRequestVer uint8 = 2

// InstanceBackfillRequestCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const InstanceBackfillRequestCmd uint16 = 50001

// InstanceBackfillRequest represents the command protocol data structure.
type InstanceBackfillRequest struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd uint16
}

// NewInstanceBackfillRequest creates a new instance of InstanceBackfillRequest struct.
func NewInstanceBackfillRequest() *InstanceBackfillRequest {
	return &InstanceBackfillRequest{Ver: 2, Cmd: 50001}
}

// Pack encodes InstanceBackfillRequest struct to a byte array to be delivered over the command.
func (proto *InstanceBackfillRequest) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	// done
	return bytes
}

// Unpack decodes the command payload byte array to InstanceBackfillRequest struct.
func (proto *InstanceBackfillRequest) Unpack(bytes []byte) error {
	unpackErr := errors.New("InstanceBackfillRequestUnpackError")
	if len(bytes) < 0 {
		return unpackErr
	}

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *InstanceBackfillRequest) PackedSize() int {
	var packedSize = 0
	return packedSize
}

func (proto *InstanceBackfillRequest) String() string {
	list := make([]string, 0)

	return strings.Join(list, " | ")
}

func (proto *InstanceBackfillRequest) GetVer() uint8 {
	return proto.Ver
}
func (proto *InstanceBackfillRequest) GetCmd() uint16 {
	return proto.Cmd
}
