// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package dgs

import (
	"errors"
	"fmt"
	"strings"
)

// InstanceAllocatedPushVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const InstanceAllocatedPushVer uint8 = 2

// InstanceAllocatedPushCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const InstanceAllocatedPushCmd uint16 = 50002

// InstanceAllocatedPush represents the command protocol data structure.
type InstanceAllocatedPush struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd uint16
	// True if the caller was in the room before the call to create DGS, false otherwise.
	IsMember bool
	// DGS allocation success value.
	Success bool
}

// NewInstanceAllocatedPush creates a new instance of InstanceAllocatedPush struct.
func NewInstanceAllocatedPush() *InstanceAllocatedPush {
	return &InstanceAllocatedPush{Ver: 2, Cmd: 50002, IsMember: false, Success: false}
}

// Pack encodes InstanceAllocatedPush struct to a byte array to be delivered over the command.
func (proto *InstanceAllocatedPush) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	var _packedBooleanBytes [1]byte
	_ = _packedBooleanBytes
	if proto.IsMember {
		_packedBooleanBytes[0] |= (1 << 0)
	}
	if proto.Success {
		_packedBooleanBytes[0] |= (1 << 1)
	}
	/* uint8 */
	bytes = append(bytes, _packedBooleanBytes[0])
	// done
	return bytes
}

// Unpack decodes the command payload byte array to InstanceAllocatedPush struct.
func (proto *InstanceAllocatedPush) Unpack(bytes []byte) error {
	unpackErr := errors.New("InstanceAllocatedPushUnpackError")
	if len(bytes) < 1 {
		return unpackErr
	}

	offset := 0

	proto.IsMember = (uint8(bytes[offset+0]) & (1 << 0)) != 0
	proto.Success = (uint8(bytes[offset+0]) & (1 << 1)) != 0
	offset += 1

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *InstanceAllocatedPush) PackedSize() int {
	var packedSize = 0
	packedSize += 1 // packed booleans length
	return packedSize
}

func (proto *InstanceAllocatedPush) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("IsMember = ", proto.IsMember))
	list = append(list, fmt.Sprint("Success = ", proto.Success))
	return strings.Join(list, " | ")
}

func (proto *InstanceAllocatedPush) GetVer() uint8 {
	return proto.Ver
}
func (proto *InstanceAllocatedPush) GetCmd() uint16 {
	return proto.Cmd
}
