// © 2019-2025 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package dgs

import (
	"errors"
	"fmt"
	"strings"
)

// InstanceBackfillResponseVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const InstanceBackfillResponseVer uint8 = 2

// InstanceBackfillResponseCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const InstanceBackfillResponseCmd uint16 = 50001

// InstanceBackfillResponse represents the command protocol data structure.
// DGS backfill response.
// The status possible values are:
//   - 0 success
//   - 1 DGS is starting. A previous call to instance create have been done and it is still ongoing.
//   - 2 DGS instance not created. The owner of the session must first call create DGS instance.
//   - 3 DGS is starting and the caller is not part of the DGS creation members request.
//     Caller will not receive a credentials push but will receive InstanceAllocatedPush
//     with IsMember=false when the creation will be finished. Caller should call backfill again
//     once this push event is received.
type InstanceBackfillResponse struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd uint16
	// DGS backfill status.
	Status uint8
}

// NewInstanceBackfillResponse creates a new instance of InstanceBackfillResponse struct.
func NewInstanceBackfillResponse() *InstanceBackfillResponse {
	return &InstanceBackfillResponse{Ver: 2, Cmd: 50001, Status: 0}
}

// Pack encodes InstanceBackfillResponse struct to a byte array to be delivered over the command.
func (proto *InstanceBackfillResponse) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	/* uint8 */
	bytes = append(bytes, proto.Status)

	// done
	return bytes
}

// Unpack decodes the command payload byte array to InstanceBackfillResponse struct.
func (proto *InstanceBackfillResponse) Unpack(bytes []byte) error {
	unpackErr := errors.New("InstanceBackfillResponseUnpackError")
	if len(bytes) < 1 {
		return unpackErr
	}

	offset := 0

	/* uint8 */
	if offset+1 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Status: %w", unpackErr)
	}
	proto.Status = uint8(bytes[offset])
	offset++

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *InstanceBackfillResponse) PackedSize() int {
	var packedSize = 0
	packedSize += 1 // Status
	return packedSize
}

func (proto *InstanceBackfillResponse) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("Status = ", proto.Status))
	return strings.Join(list, " | ")
}

func (proto *InstanceBackfillResponse) GetVer() uint8 {
	return proto.Ver
}
func (proto *InstanceBackfillResponse) GetCmd() uint16 {
	return proto.Cmd
}
