// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package dgs

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// MeshInstanceCreateRequestVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const MeshInstanceCreateRequestVer uint8 = 0

// MeshInstanceCreateRequestCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const MeshInstanceCreateRequestCmd uint16 = 0

// MeshInstanceCreateRequest represents the command protocol data structure.
type MeshInstanceCreateRequest struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd uint16
	// Member IDs of users connected to same server as host to join the DGS.
	MemberIDs []string
	// Metadata payload for instance creation (level data or whatever is needed by the DGS application).
	Metadata []byte
}

// NewMeshInstanceCreateRequest creates a new instance of MeshInstanceCreateRequest struct.
func NewMeshInstanceCreateRequest() *MeshInstanceCreateRequest {
	return &MeshInstanceCreateRequest{Ver: 0, Cmd: 0, MemberIDs: make([]string, 0), Metadata: make([]byte, 0)}
}

// Pack encodes MeshInstanceCreateRequest struct to a byte array to be delivered over the command.
func (proto *MeshInstanceCreateRequest) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	/* []string */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.MemberIDs)))
	for i := 0; i < len(proto.MemberIDs); i++ {
		bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.MemberIDs[i])))
		bytes = append(bytes, []byte(proto.MemberIDs[i])...)
	}

	/* []byte */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.Metadata)))
	bytes = append(bytes, proto.Metadata...)

	// done
	return bytes
}

// Unpack decodes the command payload byte array to MeshInstanceCreateRequest struct.
func (proto *MeshInstanceCreateRequest) Unpack(bytes []byte) error {
	unpackErr := errors.New("MeshInstanceCreateRequestUnpackError")
	if len(bytes) < 4 {
		return unpackErr
	}

	offset := 0

	/* []string */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack MemberIDs: %w", unpackErr)
	}
	memberIDsCount := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if memberIDsCount*2 /* header */ +offset+2 > len(bytes) {
		return errors.New("UnpackError")
	}
	offset += 2
	proto.MemberIDs = make([]string, 0, memberIDsCount)
	for i := 0; i < memberIDsCount; i++ {
		if offset+2 > len(bytes) {
			return fmt.Errorf("payload too short to unpack MemberIDs at index %d: %w", i, unpackErr)
		}
		size := int(binary.BigEndian.Uint16((bytes[offset : offset+2])))
		offset += 2
		if offset+size > len(bytes) {
			return fmt.Errorf("payload too short to unpack MemberIDs at index %d: %w", i, unpackErr)
		}
		proto.MemberIDs = append(proto.MemberIDs, string(bytes[offset:offset+size:offset+size]))
		offset += size
	}

	/* []byte */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Metadata: %w", unpackErr)
	}
	metadataSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if metadataSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Metadata: %w", unpackErr)
	}
	offset += 2
	proto.Metadata = make([]byte, metadataSize)
	copy(proto.Metadata, bytes[offset:offset+metadataSize:offset+metadataSize])
	offset += metadataSize

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *MeshInstanceCreateRequest) PackedSize() int {
	var packedSize = 0
	// MemberIDs
	packedSize += 2
	for i := range proto.MemberIDs {
		packedSize += 2 + len(proto.MemberIDs[i])
	}
	packedSize += 2 + len(proto.Metadata) // Metadata
	return packedSize
}

func (proto *MeshInstanceCreateRequest) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("MemberIDs = ", proto.MemberIDs))
	list = append(list, fmt.Sprint("Metadata = ", proto.Metadata))
	return strings.Join(list, " | ")
}

func (proto *MeshInstanceCreateRequest) GetVer() uint8 {
	return proto.Ver
}
func (proto *MeshInstanceCreateRequest) GetCmd() uint16 {
	return proto.Cmd
}
