// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package dgs

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// MeshInstanceRPCRequestVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const MeshInstanceRPCRequestVer uint8 = 0

// MeshInstanceRPCRequestCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const MeshInstanceRPCRequestCmd uint16 = 0

// MeshInstanceRPCRequest represents the command protocol data structure.
// If type is 'backfill' then the data will be MeshInstanceCreateRequest with only the caller user id in the memberIDs list.
// and the response will be 'MeshInstanceCreateResponseUserCredentials'.
type MeshInstanceRPCRequest struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd  uint16
	Data []byte
	Type string
}

// NewMeshInstanceRPCRequest creates a new instance of MeshInstanceRPCRequest struct.
func NewMeshInstanceRPCRequest() *MeshInstanceRPCRequest {
	return &MeshInstanceRPCRequest{Ver: 0, Cmd: 0, Data: make([]byte, 0), Type: ""}
}

// Pack encodes MeshInstanceRPCRequest struct to a byte array to be delivered over the command.
func (proto *MeshInstanceRPCRequest) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	/* []byte */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.Data)))
	bytes = append(bytes, proto.Data...)

	/* string */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.Type)))
	bytes = append(bytes, []byte(proto.Type)...)

	// done
	return bytes
}

// Unpack decodes the command payload byte array to MeshInstanceRPCRequest struct.
func (proto *MeshInstanceRPCRequest) Unpack(bytes []byte) error {
	unpackErr := errors.New("MeshInstanceRPCRequestUnpackError")
	if len(bytes) < 4 {
		return unpackErr
	}

	offset := 0

	/* []byte */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Data: %w", unpackErr)
	}
	dataSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if dataSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Data: %w", unpackErr)
	}
	offset += 2
	proto.Data = make([]byte, dataSize)
	copy(proto.Data, bytes[offset:offset+dataSize:offset+dataSize])
	offset += dataSize

	/* string */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Type: %w", unpackErr)
	}
	typeSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if typeSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Type: %w", unpackErr)
	}
	offset += 2
	proto.Type = string(bytes[offset : offset+typeSize : offset+typeSize])
	offset += typeSize

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *MeshInstanceRPCRequest) PackedSize() int {
	var packedSize = 0
	packedSize += 2 + len(proto.Data) // Data
	packedSize += 2 + len(proto.Type) // Type
	return packedSize
}

func (proto *MeshInstanceRPCRequest) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("Data = ", proto.Data))
	list = append(list, fmt.Sprint("Type = ", proto.Type))
	return strings.Join(list, " | ")
}

func (proto *MeshInstanceRPCRequest) GetVer() uint8 {
	return proto.Ver
}
func (proto *MeshInstanceRPCRequest) GetCmd() uint16 {
	return proto.Cmd
}
