// © 2019-2025 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package dgs

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// MeshInstanceCreateResponseVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const MeshInstanceCreateResponseVer uint8 = 0

// MeshInstanceCreateResponseCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const MeshInstanceCreateResponseCmd uint16 = 0

// MeshInstanceCreateResponse represents the command protocol data structure.
type MeshInstanceCreateResponse struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd uint16
	// Credentials of the session's members.
	Credentials []*MeshInstanceCreateResponseUserCredentials
}

// NewMeshInstanceCreateResponse creates a new instance of MeshInstanceCreateResponse struct.
func NewMeshInstanceCreateResponse() *MeshInstanceCreateResponse {
	return &MeshInstanceCreateResponse{Ver: 0, Cmd: 0, Credentials: make([]*MeshInstanceCreateResponseUserCredentials, 0)}
}

// Pack encodes MeshInstanceCreateResponse struct to a byte array to be delivered over the command.
func (proto *MeshInstanceCreateResponse) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	/* []MeshInstanceCreateResponseUserCredentials */
	credentialsLengthBytes := make([]byte, 2)
	credentialsLength := len(proto.Credentials)
	binary.BigEndian.PutUint16(credentialsLengthBytes, uint16(credentialsLength))
	bytes = append(bytes, credentialsLengthBytes...)
	for i := 0; i < credentialsLength; i++ {
		credentialsSizeBytes := make([]byte, 2)
		credentialsPacked := proto.Credentials[i].Pack()
		binary.BigEndian.PutUint16(credentialsSizeBytes, uint16(len(credentialsPacked)))
		bytes = append(bytes, credentialsSizeBytes...)
		bytes = append(bytes, credentialsPacked...)
	}

	// done
	return bytes
}

// Unpack decodes the command payload byte array to MeshInstanceCreateResponse struct.
func (proto *MeshInstanceCreateResponse) Unpack(bytes []byte) error {
	unpackErr := errors.New("MeshInstanceCreateResponseUnpackError")
	if len(bytes) < 2 {
		return unpackErr
	}

	offset := 0

	/* []MeshInstanceCreateResponseUserCredentials */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Credentials: %w", unpackErr)
	}
	credentialsLength := int(binary.BigEndian.Uint16((bytes[offset : offset+2])))
	offset += 2
	proto.Credentials = make([]*MeshInstanceCreateResponseUserCredentials, credentialsLength)
	for i := 0; i < credentialsLength; i++ {
		if offset+2 > len(bytes) {
			return fmt.Errorf("payload too short to unpack Credentials at index %d: %w", i, unpackErr)
		}
		credentialsSize := int(binary.BigEndian.Uint16((bytes[offset : offset+2])))
		offset += 2
		if credentialsSize+offset > len(bytes) {
			return fmt.Errorf("payload too short to unpack Credentials at index %d: %w", i, unpackErr)
		}
		credentialsBytes := bytes[offset : offset+credentialsSize : offset+credentialsSize]
		item := &MeshInstanceCreateResponseUserCredentials{Ver: 0, Cmd: 0}
		if err := item.Unpack(credentialsBytes); err != nil {
			return fmt.Errorf("payload too short to unpack Credentials at index %d: %w", i, err)
		}
		proto.Credentials[i] = item
		offset += credentialsSize
	}

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *MeshInstanceCreateResponse) PackedSize() int {
	var packedSize = 0
	// Credentials
	packedSize += 2
	for i := range proto.Credentials {
		packedSize += proto.Credentials[i].PackedSize()
	}
	return packedSize
}

func (proto *MeshInstanceCreateResponse) String() string {
	list := make([]string, 0)
	for i, item := range proto.Credentials {
		list = append(list, fmt.Sprint("Credentials[", i, "] = ", "[", item.String(), "]"))
	}
	return strings.Join(list, " | ")
}

func (proto *MeshInstanceCreateResponse) GetVer() uint8 {
	return proto.Ver
}
func (proto *MeshInstanceCreateResponse) GetCmd() uint16 {
	return proto.Cmd
}
