// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package dgs

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// RoomDGSStateVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const RoomDGSStateVer uint8 = 0

// RoomDGSStateCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const RoomDGSStateCmd uint16 = 0

// RoomDGSState represents the command protocol data structure.
// State stored in the room property to manage the lifecycle of the DGS.
type RoomDGSState struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd uint16
	// DGS identifier.
	DgsIdentifier []byte
	// Last time the data was updated.
	LastUpdateTime int64
	// Member IDs contained in the DGS creation request.
	Members []string
	// DGS state.
	State string
}

// NewRoomDGSState creates a new instance of RoomDGSState struct.
func NewRoomDGSState() *RoomDGSState {
	return &RoomDGSState{Ver: 0, Cmd: 0, DgsIdentifier: make([]byte, 0), LastUpdateTime: 0, Members: make([]string, 0), State: ""}
}

// Pack encodes RoomDGSState struct to a byte array to be delivered over the command.
func (proto *RoomDGSState) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	/* []byte */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.DgsIdentifier)))
	bytes = append(bytes, proto.DgsIdentifier...)

	/* int64 */
	bytes = binary.BigEndian.AppendUint64(bytes, uint64(proto.LastUpdateTime))

	/* []string */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.Members)))
	for i := 0; i < len(proto.Members); i++ {
		bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.Members[i])))
		bytes = append(bytes, []byte(proto.Members[i])...)
	}

	/* string */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.State)))
	bytes = append(bytes, []byte(proto.State)...)

	// done
	return bytes
}

// Unpack decodes the command payload byte array to RoomDGSState struct.
func (proto *RoomDGSState) Unpack(bytes []byte) error {
	unpackErr := errors.New("RoomDGSStateUnpackError")
	if len(bytes) < 14 {
		return unpackErr
	}

	offset := 0

	/* []byte */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack DgsIdentifier: %w", unpackErr)
	}
	dgsIdentifierSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if dgsIdentifierSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack DgsIdentifier: %w", unpackErr)
	}
	offset += 2
	proto.DgsIdentifier = make([]byte, dgsIdentifierSize)
	copy(proto.DgsIdentifier, bytes[offset:offset+dgsIdentifierSize:offset+dgsIdentifierSize])
	offset += dgsIdentifierSize

	/* int64 */
	if offset+8 > len(bytes) {
		return fmt.Errorf("payload too short to unpack LastUpdateTime: %w", unpackErr)
	}
	proto.LastUpdateTime = int64(binary.BigEndian.Uint64(bytes[offset : offset+8]))
	offset += 8

	/* []string */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Members: %w", unpackErr)
	}
	membersCount := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if membersCount*2 /* header */ +offset+2 > len(bytes) {
		return errors.New("UnpackError")
	}
	offset += 2
	proto.Members = make([]string, 0, membersCount)
	for i := 0; i < membersCount; i++ {
		if offset+2 > len(bytes) {
			return fmt.Errorf("payload too short to unpack Members at index %d: %w", i, unpackErr)
		}
		size := int(binary.BigEndian.Uint16((bytes[offset : offset+2])))
		offset += 2
		if offset+size > len(bytes) {
			return fmt.Errorf("payload too short to unpack Members at index %d: %w", i, unpackErr)
		}
		proto.Members = append(proto.Members, string(bytes[offset:offset+size:offset+size]))
		offset += size
	}

	/* string */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack State: %w", unpackErr)
	}
	stateSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if stateSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack State: %w", unpackErr)
	}
	offset += 2
	proto.State = string(bytes[offset : offset+stateSize : offset+stateSize])
	offset += stateSize

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *RoomDGSState) PackedSize() int {
	var packedSize = 0
	packedSize += 2 + len(proto.DgsIdentifier) // DgsIdentifier
	packedSize += 8                            // LastUpdateTime
	// Members
	packedSize += 2
	for i := range proto.Members {
		packedSize += 2 + len(proto.Members[i])
	}
	packedSize += 2 + len(proto.State) // State
	return packedSize
}

func (proto *RoomDGSState) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("DgsIdentifier = ", proto.DgsIdentifier))
	list = append(list, fmt.Sprint("LastUpdateTime = ", proto.LastUpdateTime))
	list = append(list, fmt.Sprint("Members = ", proto.Members))
	list = append(list, fmt.Sprint("State = ", proto.State))
	return strings.Join(list, " | ")
}

func (proto *RoomDGSState) GetVer() uint8 {
	return proto.Ver
}
func (proto *RoomDGSState) GetCmd() uint16 {
	return proto.Cmd
}
