namespace: base

labels:
  - includeSelectors: true
    pairs:
      app: diarkis

# build target
resources:
  - udp/deploy.yaml
  - udp/hpa.yaml
  - tcp/deploy.yaml
  - tcp/hpa.yaml
  - mars/sts.yaml
  - mars/svc.yaml
  - http/deploy.yaml
  - http/svc.yaml
  - http/hpa.yaml
  - ns.yaml

configMapGenerator:
  - name: shared-conf
    files:
      - shared/conf/field.json
      - shared/conf/group.json
      - shared/conf/log.json
      - shared/conf/matching.json
      - shared/conf/mesh.json
      - shared/conf/dm.json
      - shared/conf/dive.json

  - name: http-conf
    files:
      - http/conf/main.json

  - name: udp-conf
    files:
      - udp/conf/main.json

  - name: tcp-conf
    files:
      - tcp/conf/main.json

  - name: mars-conf
    files:
      - mars/conf/default.conf.json

  - name: hc-conf
    files:
      - hc/conf/health-check.json
