// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Puffer v0.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package room

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// BroadcastLoDVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const BroadcastLoDVer uint8 = 2

// BroadcastLoDCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const BroadcastLoDCmd uint16 = 1001

// BroadcastLoD represents the command protocol data structure.
// Broadcast the LoD data to the room. Synchronize data more frequently with nearby characters, and less frequently with distant characters.
type BroadcastLoD struct {
	// Data for synchronization
	Payload []byte
	// The x coordinate of the local character
	X int32
	// The y coordinate of the local character
	Y int32
}

// NewBroadcastLoD creates a new instance of BroadcastLoD struct.
func NewBroadcastLoD() *BroadcastLoD {
	return &BroadcastLoD{}
}

// Pack encodes BroadcastLoD struct to a byte array to be delivered over the command.
func (proto *BroadcastLoD) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.Payload)))
	bytes = append(bytes, proto.Payload...)
	bytes = binary.BigEndian.AppendUint32(bytes, uint32(proto.X))
	bytes = binary.BigEndian.AppendUint32(bytes, uint32(proto.Y))
	return bytes
}

// Unpack decodes the command payload byte array to BroadcastLoD struct.
func (proto *BroadcastLoD) Unpack(bytes []byte) error {
	unpackErr := errors.New("BroadcastLoDUnpackError")
	if len(bytes) < 10 {
		return unpackErr
	}
	offset := 0
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Payload: %w", unpackErr)
	}
	payloadSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if payloadSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Payload: %w", unpackErr)
	}
	offset += 2
	proto.Payload = make([]byte, payloadSize)
	copy(proto.Payload, bytes[offset:offset+payloadSize:offset+payloadSize])
	offset += payloadSize
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack X: %w", unpackErr)
	}
	proto.X = int32(binary.BigEndian.Uint32(bytes[offset : offset+4]))
	offset += 4
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Y: %w", unpackErr)
	}
	proto.Y = int32(binary.BigEndian.Uint32(bytes[offset : offset+4]))
	offset += 4
	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *BroadcastLoD) PackedSize() int {
	var packedSize = 0
	packedSize += 2 + len(proto.Payload)
	packedSize += 4
	packedSize += 4
	return packedSize
}

func (proto *BroadcastLoD) String() string {
	var list []string
	list = append(list, fmt.Sprint("Payload = ", proto.Payload))
	list = append(list, fmt.Sprint("X = ", proto.X))
	list = append(list, fmt.Sprint("Y = ", proto.Y))
	return strings.Join(list, " | ")
}

// Ver returns the protocol's command version.
func (proto *BroadcastLoD) Ver() uint8 {
	return BroadcastLoDVer
}

// Cmd returns the protocol's command ID.
func (proto *BroadcastLoD) Cmd() uint16 {
	return BroadcastLoDCmd
}
