// © 2019-2026 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Puffer v0.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package room

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// BroadcastLoDPushVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const BroadcastLoDPushVer uint8 = 2

// BroadcastLoDPushCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const BroadcastLoDPushCmd uint16 = 1001

// BroadcastLoDPush represents the command protocol data structure.
// Push the LoD data to the client.
type BroadcastLoDPush struct {
	// Data for synchronization
	Payload []byte
}

// NewBroadcastLoDPush creates a new instance of BroadcastLoDPush struct.
func NewBroadcastLoDPush() *BroadcastLoDPush {
	return &BroadcastLoDPush{}
}

// Pack encodes BroadcastLoDPush struct to a byte array to be delivered over the command.
func (proto *BroadcastLoDPush) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.Payload)))
	bytes = append(bytes, proto.Payload...)
	return bytes
}

// Unpack decodes the command payload byte array to BroadcastLoDPush struct.
func (proto *BroadcastLoDPush) Unpack(bytes []byte) error {
	unpackErr := errors.New("BroadcastLoDPushUnpackError")
	if len(bytes) < 2 {
		return unpackErr
	}
	offset := 0
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Payload: %w", unpackErr)
	}
	payloadSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if payloadSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Payload: %w", unpackErr)
	}
	offset += 2
	proto.Payload = make([]byte, payloadSize)
	copy(proto.Payload, bytes[offset:offset+payloadSize:offset+payloadSize])
	offset += payloadSize
	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *BroadcastLoDPush) PackedSize() int {
	var packedSize = 0
	packedSize += 2 + len(proto.Payload)
	return packedSize
}

func (proto *BroadcastLoDPush) String() string {
	var list []string
	list = append(list, fmt.Sprint("Payload = ", proto.Payload))
	return strings.Join(list, " | ")
}

// Ver returns the protocol's command version.
func (proto *BroadcastLoDPush) Ver() uint8 {
	return BroadcastLoDPushVer
}

// Cmd returns the protocol's command ID.
func (proto *BroadcastLoDPush) Cmd() uint16 {
	return BroadcastLoDPushCmd
}
