// © 2019-2025 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package room

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// BroadcastLoDPushVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const BroadcastLoDPushVer uint8 = 2

// BroadcastLoDPushCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const BroadcastLoDPushCmd uint16 = 1001

// BroadcastLoDPush represents the command protocol data structure.
// Push the LoD data to the client.
type BroadcastLoDPush struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd uint16
	// Data for synchronization
	Payload []byte
}

// NewBroadcastLoDPush creates a new instance of BroadcastLoDPush struct.
func NewBroadcastLoDPush() *BroadcastLoDPush {
	return &BroadcastLoDPush{Ver: 2, Cmd: 1001, Payload: make([]byte, 0)}
}

// Pack encodes BroadcastLoDPush struct to a byte array to be delivered over the command.
func (proto *BroadcastLoDPush) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	/* []byte */
	bytes = binary.BigEndian.AppendUint16(bytes, uint16(len(proto.Payload)))
	bytes = append(bytes, proto.Payload...)

	// done
	return bytes
}

// Unpack decodes the command payload byte array to BroadcastLoDPush struct.
func (proto *BroadcastLoDPush) Unpack(bytes []byte) error {
	unpackErr := errors.New("BroadcastLoDPushUnpackError")
	if len(bytes) < 2 {
		return unpackErr
	}

	offset := 0

	/* []byte */
	if offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Payload: %w", unpackErr)
	}
	payloadSize := int(binary.BigEndian.Uint16(bytes[offset : offset+2]))
	if payloadSize+offset+2 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Payload: %w", unpackErr)
	}
	offset += 2
	proto.Payload = make([]byte, payloadSize)
	copy(proto.Payload, bytes[offset:offset+payloadSize:offset+payloadSize])
	offset += payloadSize

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *BroadcastLoDPush) PackedSize() int {
	var packedSize = 0
	packedSize += 2 + len(proto.Payload) // Payload
	return packedSize
}

func (proto *BroadcastLoDPush) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("Payload = ", proto.Payload))
	return strings.Join(list, " | ")
}

func (proto *BroadcastLoDPush) GetVer() uint8 {
	return proto.Ver
}
func (proto *BroadcastLoDPush) GetCmd() uint16 {
	return proto.Cmd
}
