// © 2019-2026 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Puffer v0.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package room

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// GetLoDInfoResponseVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const GetLoDInfoResponseVer uint8 = 2

// GetLoDInfoResponseCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const GetLoDInfoResponseCmd uint16 = 1002

// GetLoDInfoResponse represents the command protocol data structure.
// Response the LoD information of the room.
type GetLoDInfoResponse struct {
	// The maximum distance for far characters (centimeters)
	MaxDistanceForFar int32
	// The maximum distance for nearby characters (centimeters)
	MaxDistanceForNearby int32
	// Synchronization interval for far characters (milliseconds)
	SyncIntervalForFar int32
	// Synchronization interval for nearby characters (milliseconds)
	SyncIntervalForNearby int32
}

// NewGetLoDInfoResponse creates a new instance of GetLoDInfoResponse struct.
func NewGetLoDInfoResponse() *GetLoDInfoResponse {
	return &GetLoDInfoResponse{}
}

// Pack encodes GetLoDInfoResponse struct to a byte array to be delivered over the command.
func (proto *GetLoDInfoResponse) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())
	bytes = binary.BigEndian.AppendUint32(bytes, uint32(proto.MaxDistanceForFar))
	bytes = binary.BigEndian.AppendUint32(bytes, uint32(proto.MaxDistanceForNearby))
	bytes = binary.BigEndian.AppendUint32(bytes, uint32(proto.SyncIntervalForFar))
	bytes = binary.BigEndian.AppendUint32(bytes, uint32(proto.SyncIntervalForNearby))
	return bytes
}

// Unpack decodes the command payload byte array to GetLoDInfoResponse struct.
func (proto *GetLoDInfoResponse) Unpack(bytes []byte) error {
	unpackErr := errors.New("GetLoDInfoResponseUnpackError")
	if len(bytes) < 16 {
		return unpackErr
	}
	offset := 0
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack MaxDistanceForFar: %w", unpackErr)
	}
	proto.MaxDistanceForFar = int32(binary.BigEndian.Uint32(bytes[offset : offset+4]))
	offset += 4
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack MaxDistanceForNearby: %w", unpackErr)
	}
	proto.MaxDistanceForNearby = int32(binary.BigEndian.Uint32(bytes[offset : offset+4]))
	offset += 4
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack SyncIntervalForFar: %w", unpackErr)
	}
	proto.SyncIntervalForFar = int32(binary.BigEndian.Uint32(bytes[offset : offset+4]))
	offset += 4
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack SyncIntervalForNearby: %w", unpackErr)
	}
	proto.SyncIntervalForNearby = int32(binary.BigEndian.Uint32(bytes[offset : offset+4]))
	offset += 4
	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *GetLoDInfoResponse) PackedSize() int {
	var packedSize = 0
	packedSize += 4
	packedSize += 4
	packedSize += 4
	packedSize += 4
	return packedSize
}

func (proto *GetLoDInfoResponse) String() string {
	var list []string
	list = append(list, fmt.Sprint("MaxDistanceForFar = ", proto.MaxDistanceForFar))
	list = append(list, fmt.Sprint("MaxDistanceForNearby = ", proto.MaxDistanceForNearby))
	list = append(list, fmt.Sprint("SyncIntervalForFar = ", proto.SyncIntervalForFar))
	list = append(list, fmt.Sprint("SyncIntervalForNearby = ", proto.SyncIntervalForNearby))
	return strings.Join(list, " | ")
}

// Ver returns the protocol's command version.
func (proto *GetLoDInfoResponse) Ver() uint8 {
	return GetLoDInfoResponseVer
}

// Cmd returns the protocol's command ID.
func (proto *GetLoDInfoResponse) Cmd() uint16 {
	return GetLoDInfoResponseCmd
}
