// © 2019-2026 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Puffer v0.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package room

// GetLoDInfoVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const GetLoDInfoVer uint8 = 2

// GetLoDInfoCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const GetLoDInfoCmd uint16 = 1002

// GetLoDInfo represents the command protocol data structure.
// Get the LoD information of the room.
type GetLoDInfo struct {
}

// NewGetLoDInfo creates a new instance of GetLoDInfo struct.
func NewGetLoDInfo() *GetLoDInfo {
	return &GetLoDInfo{}
}

// Pack encodes GetLoDInfo struct to a byte array to be delivered over the command.
func (proto *GetLoDInfo) Pack() []byte {
	return nil
}

// Unpack decodes the command payload byte array to GetLoDInfo struct.
func (proto *GetLoDInfo) Unpack(bytes []byte) error {
	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *GetLoDInfo) PackedSize() int {
	return 0
}

func (proto *GetLoDInfo) String() string {
	return ""
}

// Ver returns the protocol's command version.
func (proto *GetLoDInfo) Ver() uint8 {
	return GetLoDInfoVer
}

// Cmd returns the protocol's command ID.
func (proto *GetLoDInfo) Cmd() uint16 {
	return GetLoDInfoCmd
}
