// © 2019-2025 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package room

import (
	"errors"
	"strings"
)

// GetLoDInfoVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const GetLoDInfoVer uint8 = 2

// GetLoDInfoCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const GetLoDInfoCmd uint16 = 1002

// GetLoDInfo represents the command protocol data structure.
// Get the LoD information of the room.
type GetLoDInfo struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd uint16
}

// NewGetLoDInfo creates a new instance of GetLoDInfo struct.
func NewGetLoDInfo() *GetLoDInfo {
	return &GetLoDInfo{Ver: 2, Cmd: 1002}
}

// Pack encodes GetLoDInfo struct to a byte array to be delivered over the command.
func (proto *GetLoDInfo) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	// done
	return bytes
}

// Unpack decodes the command payload byte array to GetLoDInfo struct.
func (proto *GetLoDInfo) Unpack(bytes []byte) error {
	unpackErr := errors.New("GetLoDInfoUnpackError")
	if len(bytes) < 0 {
		return unpackErr
	}

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *GetLoDInfo) PackedSize() int {
	var packedSize = 0
	return packedSize
}

func (proto *GetLoDInfo) String() string {
	list := make([]string, 0)

	return strings.Join(list, " | ")
}

func (proto *GetLoDInfo) GetVer() uint8 {
	return proto.Ver
}
func (proto *GetLoDInfo) GetCmd() uint16 {
	return proto.Cmd
}
