// © 2019-2025 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package room

import (
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// GetLoDInfoResponseVer represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const GetLoDInfoResponseVer uint8 = 2

// GetLoDInfoResponseCmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const GetLoDInfoResponseCmd uint16 = 1002

// GetLoDInfoResponse represents the command protocol data structure.
// Response the LoD information of the room.
type GetLoDInfoResponse struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd uint16
	// The maximum distance for far characters (centimeters)
	MaxDistanceForFar int32
	// The maximum distance for nearby characters (centimeters)
	MaxDistanceForNearby int32
	// Synchronization interval for far characters (milliseconds)
	SyncIntervalForFar int32
	// Synchronization interval for nearby characters (milliseconds)
	SyncIntervalForNearby int32
}

// NewGetLoDInfoResponse creates a new instance of GetLoDInfoResponse struct.
func NewGetLoDInfoResponse() *GetLoDInfoResponse {
	return &GetLoDInfoResponse{Ver: 2, Cmd: 1002, MaxDistanceForFar: 0, MaxDistanceForNearby: 0, SyncIntervalForFar: 0, SyncIntervalForNearby: 0}
}

// Pack encodes GetLoDInfoResponse struct to a byte array to be delivered over the command.
func (proto *GetLoDInfoResponse) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	/* int32 */
	bytes = binary.BigEndian.AppendUint32(bytes, uint32(proto.MaxDistanceForFar))

	/* int32 */
	bytes = binary.BigEndian.AppendUint32(bytes, uint32(proto.MaxDistanceForNearby))

	/* int32 */
	bytes = binary.BigEndian.AppendUint32(bytes, uint32(proto.SyncIntervalForFar))

	/* int32 */
	bytes = binary.BigEndian.AppendUint32(bytes, uint32(proto.SyncIntervalForNearby))

	// done
	return bytes
}

// Unpack decodes the command payload byte array to GetLoDInfoResponse struct.
func (proto *GetLoDInfoResponse) Unpack(bytes []byte) error {
	unpackErr := errors.New("GetLoDInfoResponseUnpackError")
	if len(bytes) < 16 {
		return unpackErr
	}

	offset := 0

	/* int32 */
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack MaxDistanceForFar: %w", unpackErr)
	}
	proto.MaxDistanceForFar = int32(binary.BigEndian.Uint32(bytes[offset : offset+4]))
	offset += 4

	/* int32 */
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack MaxDistanceForNearby: %w", unpackErr)
	}
	proto.MaxDistanceForNearby = int32(binary.BigEndian.Uint32(bytes[offset : offset+4]))
	offset += 4

	/* int32 */
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack SyncIntervalForFar: %w", unpackErr)
	}
	proto.SyncIntervalForFar = int32(binary.BigEndian.Uint32(bytes[offset : offset+4]))
	offset += 4

	/* int32 */
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack SyncIntervalForNearby: %w", unpackErr)
	}
	proto.SyncIntervalForNearby = int32(binary.BigEndian.Uint32(bytes[offset : offset+4]))
	offset += 4

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *GetLoDInfoResponse) PackedSize() int {
	var packedSize = 0
	packedSize += 4 // MaxDistanceForFar
	packedSize += 4 // MaxDistanceForNearby
	packedSize += 4 // SyncIntervalForFar
	packedSize += 4 // SyncIntervalForNearby
	return packedSize
}

func (proto *GetLoDInfoResponse) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("MaxDistanceForFar = ", proto.MaxDistanceForFar))
	list = append(list, fmt.Sprint("MaxDistanceForNearby = ", proto.MaxDistanceForNearby))
	list = append(list, fmt.Sprint("SyncIntervalForFar = ", proto.SyncIntervalForFar))
	list = append(list, fmt.Sprint("SyncIntervalForNearby = ", proto.SyncIntervalForNearby))
	return strings.Join(list, " | ")
}

func (proto *GetLoDInfoResponse) GetVer() uint8 {
	return proto.Ver
}
func (proto *GetLoDInfoResponse) GetCmd() uint16 {
	return proto.Cmd
}
