apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mars
spec:
  serviceName: "mars"
  replicas: 1
  selector:
    matchLabels:
      component: mars
  template:
    metadata:
      labels:
        component: mars
    spec:
      containers:
      - name: mars
        image: mars
        # env:
        # - name: DIARKIS_PROJECT_ID
        #   value: SAMPLE_PROJECT_ID
        ports:
        - containerPort: 6779
          name: mars
        volumeMounts:
        - name: mars-conf
          mountPath: /bin/mars
        - name: hc-conf
          mountPath: /bin/tools/configs
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true          
      - name: log-collector
        image: fluent/fluent-bit:1.9.3
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /tmp/fluentd.json
        volumeMounts:
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true          
        - name: fluentd-cred
          mountPath: /tmp/
          readOnly: true
        - name: fluent-bit-conf
          mountPath: /fluent-bit/etc/
      volumes:
        - name: mars-conf
          configMap:
            name: mars-conf
        - name: hc-conf
          configMap:
            name: hc-conf
        - name: fluent-bit-conf
          configMap:
            name: fluent-bit-conf
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: fluentd-cred
          secret:
            secretName: fluentd-cred
