apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
spec:
  template:
    spec:
      containers:
      - name: http
        image: http
        resources:
          limits:
            cpu: "100m"
          requests:
            cpu: "100m"
        securityContext:
          runAsUser: 1000
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
        env:
         - name: DIARKIS_CLOUD_ENV
           value: GCP
             
