apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mars
spec:
  serviceName: "mars"
  replicas: 1
  selector:
    matchLabels:
      component: mars
  template:
    metadata:
      labels:
        component: mars
    spec:
      containers:
      - name: mars
        env:
        - name: DIARKIS_PROJECT_ID
          value: SAMPLE_PROJECT_ID
        ports:
        - containerPort: 6779
          name: mars
        volumeMounts:
        - name: mars-conf
          mountPath: /bin/mars
        - name: hc-conf
          mountPath: /bin/tools/configs
      volumes:
        - name: mars-conf
          configMap:
            name: mars-conf
        - name: hc-conf
          configMap:
            name: hc-conf

