apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws
  labels:
    component: ws
spec:
  template:
    spec:
      hostNetwork: true
      containers:
      - name: ws
        image: ws
        resources:
          limits:
            cpu: "200m"
          requests:
            cpu: "200m"
        securityContext:
          runAsUser: 1000
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
        env:
          - name: DIARKIS_CLOUD_ENV
            value: GCP
