apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp
  labels:
    component: udp
spec:
  template:
    spec:
      hostNetwork: true
      containers:
        - name: udp
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "1"
          securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            privileged: false
