apiVersion: v1
kind: Service
metadata:
  name: http
  labels:
    component: http
spec:
  type: NodePort
  selector:
    component: http
  ports:
  - port: 80
    targetPort: 7000
    name: http
    protocol: TCP
