// © 2019-2025 Diarkis Inc. All rights reserved.

// Code generated by Diarkis Puffer module: DO NOT EDIT.
//
// Auto-generated by Diarkis Version 1.1.0
//
// - Maximum length of a string is 65535 bytes
// - Maximum length of a byte array is 65535 bytes
// - Maximum length of any array is 65535 elements

//lint:file-ignore SA4024 Ignore all code, it's generated.

package custom

import (
	"encoding/binary"
	"errors"
	"fmt"
	"math"
	"strings"
)

// DiarkisVector3Ver represents the ver of the protocol's command.
//
//	[NOTE] The value is optional and if ver is not given in the definition JSON, it will be 0.
const DiarkisVector3Ver uint8 = 0

// DiarkisVector3Cmd represents the command ID of the protocol's command ID.
//
//	[NOTE] The value is optional and if cmd is not given in the definition JSON, it will be 0.
const DiarkisVector3Cmd uint16 = 0

// DiarkisVector3 represents the command protocol data structure.
type DiarkisVector3 struct {
	// Command version of the protocol
	Ver uint8
	// Command ID of the protocol
	Cmd uint16
	X   float32
	Y   float32
	Z   float32
}

// NewDiarkisVector3 creates a new instance of DiarkisVector3 struct.
func NewDiarkisVector3() *DiarkisVector3 {
	return &DiarkisVector3{Ver: 0, Cmd: 0, X: 0, Y: 0, Z: 0}
}

// Pack encodes DiarkisVector3 struct to a byte array to be delivered over the command.
func (proto *DiarkisVector3) Pack() []byte {
	bytes := make([]byte, 0, proto.PackedSize())

	/* float32 */
	bytes = binary.BigEndian.AppendUint32(bytes, math.Float32bits(proto.X))

	/* float32 */
	bytes = binary.BigEndian.AppendUint32(bytes, math.Float32bits(proto.Y))

	/* float32 */
	bytes = binary.BigEndian.AppendUint32(bytes, math.Float32bits(proto.Z))

	// done
	return bytes
}

// Unpack decodes the command payload byte array to DiarkisVector3 struct.
func (proto *DiarkisVector3) Unpack(bytes []byte) error {
	unpackErr := errors.New("DiarkisVector3UnpackError")
	if len(bytes) < 12 {
		return unpackErr
	}

	offset := 0

	/* float32 */
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack X: %w", unpackErr)
	}
	xBits := binary.BigEndian.Uint32(bytes[offset : offset+4])
	offset += 4
	proto.X = math.Float32frombits(xBits)

	/* float32 */
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Y: %w", unpackErr)
	}
	yBits := binary.BigEndian.Uint32(bytes[offset : offset+4])
	offset += 4
	proto.Y = math.Float32frombits(yBits)

	/* float32 */
	if offset+4 > len(bytes) {
		return fmt.Errorf("payload too short to unpack Z: %w", unpackErr)
	}
	zBits := binary.BigEndian.Uint32(bytes[offset : offset+4])
	offset += 4
	proto.Z = math.Float32frombits(zBits)

	return nil
}

// PackedSize returns the estimated packed size of the struct.
func (proto *DiarkisVector3) PackedSize() int {
	var packedSize = 0
	packedSize += 4 // X
	packedSize += 4 // Y
	packedSize += 4 // Z
	return packedSize
}

func (proto *DiarkisVector3) String() string {
	list := make([]string, 0)
	list = append(list, fmt.Sprint("X = ", proto.X))
	list = append(list, fmt.Sprint("Y = ", proto.Y))
	list = append(list, fmt.Sprint("Z = ", proto.Z))
	return strings.Join(list, " | ")
}

func (proto *DiarkisVector3) GetVer() uint8 {
	return proto.Ver
}
func (proto *DiarkisVector3) GetCmd() uint16 {
	return proto.Cmd
}
