apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
spec:
  template:
    spec:
      containers:
        - name: http
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "1"
          securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            privileged: false
