buildSettings:
  root: .
  goVersion: 1.16.5
  env:
    GOOS:
    GOARCH:
    CGO_CFLAGS: -I${PROJECT_DIR}
    CGO_LDFLAGS: -L${PROJECT_DIR} -Wl,-rpath,${PROJECT_DIR}
  projects:
    http:
      target: servers/http/main.go
      output: remote_bin/http
    udp:
      target: servers/udp/main.go
      output: remote_bin/udp
    tcp:
      target: servers/tcp/main.go
      output: remote_bin/tcp
    ws:
      target: servers/ws/main.go
      output: remote_bin/ws
    mars:
      target: mars/main.go
      output: remote_bin/mars
    health-check:
      target: healthcheck/main.go
      output: remote_bin/health-check
    connector:
      target: connector/main.go
      output: remote_bin/connector
diarkis:
  project_id: {{PROJECT_ID}}
  builder_token: {{BUILD_TOKEN}}
