namespace: __NAMESPACE__
bases:
  - ../../../base

# build target
patches:
  - http/deploy.yaml
  - http/ingress.yaml
  - http/svc.yaml
  - udp/deploy.yaml
  - tcp/deploy.yaml
  - mars/sts.yaml

images:
- name: udp
  newName: asia.gcr.io/__GCP_PROJECT_ID__/udp
  newTag: latest
- name: tcp
  newName: asia.gcr.io/__GCP_PROJECT_ID__/tcp
  newTag: latest
- name: mars
  newName: asia.gcr.io/__GCP_PROJECT_ID__/mars
  newTag: latest
- name: http
  newName: asia.gcr.io/__GCP_PROJECT_ID__/http      
  newTag: latest
- name: ws
  newName: asia.gcr.io/__GCP_PROJECT_ID__/ws
  newTag: latest  
  
configMapGenerator:
- name: shared-conf
  behavior: replace
  files:
    - shared/conf/field.json
    - shared/conf/group.json
    - shared/conf/log.json
    - shared/conf/matching.json
    - shared/conf/mesh.json
    
- name: http-conf
  behavior: replace
  files:
    - http/conf/main.json
    
- name: udp-conf
  behavior: replace  
  files:
    - udp/conf/main.json

- name: tcp-conf
  behavior: replace  
  files:
    - tcp/conf/main.json

- name: fluent-bit-conf
  behavior: merge
  files:
    - mars/conf/input-kubernetes.conf

- name: mars-conf
  behavior: replace
  files:
    - mars/conf/default.conf.json
