name: server-lint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          # Semantic version range syntax or exact version of Go
          go-version: "1.24.x"

      - name: init test
        # check make init command does not fail
        run: make init project_id=PROJECT_ID builder_token=BUILDER_TOKEN output=/tmp/init-test

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.3"

      - name: Install kustomize
        run: go install sigs.k8s.io/kustomize/kustomize/v5@latest

      - name: Build kustomize overlays
        run: |
          cd src
          for provider in aws azure gcp linode; do
            kustomize build k8s/${provider}/overlays/dev0 >/dev/null
          done

      - name: check format
        run: make fmt

      - name: check diff
        run: git diff --exit-code
