name: server-lint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          # Semantic version range syntax or exact version of Go
          go-version: "1.21.x"

      - name: init test
        # check make init command does not fail
        run: make init project_id=PROJECT_ID builder_token=BUILDER_TOKEN output=/tmp/init-test

      - name: check format
        run: make fmt

      - name: check diff
        run: git diff --exit-code
