apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: tcp
          resources:
            requests:
              cpu: 3500m
            limits:
              cpu: 3500m